UPDATE CLIN_FAR_PARAM 
SET FPAR_MODIFICABLE = 'S'
WHERE FPAR_MODIFICABLE = 'Y';

UPDATE CLIN_FAR_PARAM 
SET FPAR_MODIFICABLE = 'N'
WHERE FPAR_MODIFICABLE = 'n';

UPDATE CLIN_FAR_PARAM 
SET FPAR_MODIFICABLE = 'N'
WHERE FPAR_MODIFICABLE IS NULL;

/
