UPDATE CLIN_FAR_PRESENTACION_MED SET ESACODIGO=1, CMECODIGO=2;
UPDATE CLIN_FAR_PRINCIPIO_ACT SET ESACODIGO=1, CMECODIGO=2;
UPDATE CLIN_FAR_PARAM SET FPAR_ESACODIGO=1, FPAR_CMECODIGO=2 WHERE fpar_codigo > 0 and fpar_tipo = 41;