package main

import (
	"fmt"
	"log"
	"net/http"

	"github.com/joho/godotenv"

	controller "sonda.com/logistico/Modulos/controller"
	logs "sonda.com/logistico/logging"
	mdw "sonda.com/logistico/middleware"
)

func main() {
	// CARGAR VARIABLES DE ENTORNO
	err := godotenv.Load()
	if err != nil {
		log.Fatal("No puede cargar variables de entorno", err.Error())
	}

	// CONFIGURAR LOGS
	logs.InicializarLoggers(logs.MainLogger, logs.Fin700Logger, logs.BDConnectionLogger)
	tipoLogger := logs.MainLogger
	logger := logs.ObtenerLogger(tipoLogger)

	http.HandleFunc("/", mdw.PanicRecovery(tipoLogger, mdw.Preflight(controller.EchoString)))

	// Modulos de interfaz
	http.HandleFunc("/enviarmovimientosfin700", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.EnviarmovimientosFin700))))
	// http.HandleFunc("/enviarmovimientosfin702", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.EnviarmovimientosFin702))))
	http.HandleFunc("/enviarmovimientosFin700Masivo", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.EnviarmovimientosFin700Masivo))))
	http.HandleFunc("/dispensacionRecetalegado", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.DispensacionRecetalegado))))
	http.HandleFunc("/transmicionrecetalegadomasivo", mdw.PanicRecovery(tipoLogger, mdw.Preflight(controller.TransmicionRecetaLegadoMasivo)))
	http.HandleFunc("/enviacargossisalud", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.EnviarCargosSisaludModal))))
	http.HandleFunc("/listarmovimientointerfaz", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.ListarMovimientoInterfaz))))
	http.HandleFunc("/listarmovimientointerfazbodegas", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.ListarMovimientoInterfazBodegas))))
	http.HandleFunc("/listarmovimientointerfazcargo", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.ListarMovimientoInterfazCargo))))
	http.HandleFunc("/wsLogIntegraPedido", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.WsLogIntegraPedido))))
	http.HandleFunc("/consultaPaciente", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.ConsultaPaciente))))
	http.HandleFunc("/consultaCuentaPaciente", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.ConsultaCuentaPaciente))))
	http.HandleFunc("/consultaCuentaMasivo", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.ConsultaCuentaMasivo))))
	http.HandleFunc("/consultaCargoCuenta", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.ConsultaCargoCuenta))))
	http.HandleFunc("/consultaReceta", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.ConsultaReceta))))
	http.HandleFunc("/consultaSolicitudPaciente", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.ConsultaSolicitudPaciente))))
	http.HandleFunc("/tipoproducto", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.TipoProducto))))

	http.HandleFunc("/listarmovimientointerfazbodegascab", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.ListarMovimientoInterfazBodegasCab))))
	http.HandleFunc("/listarmovimientointerfazpacientecab", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.ListarMovimientoInterfazPacienteCab))))

	// Modulos de Solisitud de Consumos
	http.HandleFunc("/buscarsolicitudconsumocabecera", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.BuscarSolicitudConsumoCabecera))))
	http.HandleFunc("/buscarplantillaconsumo", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.BuscarPlantillaConsumo))))
	http.HandleFunc("/grabarplantillaconsumo", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.GrabarPlantillaConsumo))))
	http.HandleFunc("/buscarsolicitudconsumo", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.BuscarSolicitudConsumo))))
	http.HandleFunc("/grabarsolicitudconsumo", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.GrabarSolicitudConsumo))))
	http.HandleFunc("/eliminarsolicitudconsumo", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.EliminarSolicitudConsumo))))
	http.HandleFunc("/eliminarplantillaconsumo", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.EliminarPlantillaConsumo))))
	http.HandleFunc("/eliminardetalleplantillaconsumo", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.EliminarDetallePlantillaConsumo))))
	http.HandleFunc("/eliminardetallearticulosolicitudconsumo", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.EliminarDetalleArticuloSolicitudConsumo))))
	http.HandleFunc("/eliminardetallearticuloplantillaconsumo", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.EliminarDetalleArticuloPlantillaConsumo))))
	http.HandleFunc("/buscargrupoconsumo", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.BuscarGrupoConsumo))))
	http.HandleFunc("/buscarsubgrupoconsumo", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.BuscarSubGrupoConsumo))))
	http.HandleFunc("/buscarproductosconsumo", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.BuscarProductosConsumo))))
	http.HandleFunc("/buscarunidadesorganizacionales", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.BuscarUnidadesOrganizacionales))))

	// Modulos de Informes
	http.HandleFunc("/obtieneurlinfordencompra", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.ObtieneURLInfOrdenCompra))))
	http.HandleFunc("/obtieneurlinflistaconteoinventario", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.ObtieneURLinfListaConteoInventario))))
	http.HandleFunc("/obtieneurlinfexistenciasvalorizadas", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.ObtieneURLinfExistenciasValorizadas))))
	http.HandleFunc("/obtieneurlinfbodegasvalorizadas", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.ObtieneURLinfBodegasValorizadas))))
	http.HandleFunc("/obtieneurlinfajustevalorizado", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.ObtieneURLinfAjusteValorizado))))
	http.HandleFunc("/obtieneurlinfmovimientosinternos", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.ObtieneURLinfMovimientosInternos))))
	http.HandleFunc("/obtieneurlinfpreciosproductos", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.ObtieneURLinfPreciosProductos))))
	http.HandleFunc("/obtieneurlinfreposicionbodegas", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.ObtieneURLinfReposicionBodegas))))
	http.HandleFunc("/obtieneurlinfajustesprecios", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.ObtieneURLinfAjustesPrecios))))
	http.HandleFunc("/obtieneurlinfalfabeticoproducto", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.ObtieneURLinfAlfabeticoProducto))))
	http.HandleFunc("/obtieneurlinfconsumobodegavalo", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.ObtieneURLinfConsumoBodegaValo))))
	http.HandleFunc("/obtieneurlinfconsolidadodevoluciones", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.ObtieneURLinfConsolidadoDevoluciones))))
	http.HandleFunc("/obtieneurlinftendenciaconsumo", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.ObtieneURLinfTendenciaConsumo))))
	http.HandleFunc("/obtieneurlinfauditoriaprecios", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.ObtieneURLinfAuditoriaPrecios))))
	http.HandleFunc("/obtieneurlinfcoberturageneral", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.ObtieneURLinfCoberturaGeneral))))
	http.HandleFunc("/obtieneurlinfdespachobodegas", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.ObtieneURLinfDespachoBodegas))))
	http.HandleFunc("/obtieneurlinfconsumobodega", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.ObtieneURLinfConsumoBodega))))
	http.HandleFunc("/obtieneurlinfestadoordencompra", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.ObtieneURLinfEstadoOrdenCompra))))
	http.HandleFunc("/obtieneurlinfordenpendiente", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.ObtieneURLinfOrdenPendiente))))
	http.HandleFunc("/obtieneurlinfordencompraanulada", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.ObtieneURLinfOrdenCompraAnulada))))
	http.HandleFunc("/obtieneurlinfordencompracerradaman", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.ObtieneURLinfOrdenCompraCerradaMan))))
	http.HandleFunc("/obtieneurlinfdetalleordencompra", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.ObtieneURLinfDetalleOrdenCompra))))
	http.HandleFunc("/obtieneurlinfrankingcomprasproveedor", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.ObtieneURLinfRankingComprasProveedor))))
	http.HandleFunc("/obtieneurlinfcomprasproveedor", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.ObtieneURLinfComprasProveedor))))
	http.HandleFunc("/obtieneurlinfdocumentosingresados", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.ObtieneURLinfDocumentosIngresados))))
	http.HandleFunc("/obtieneurlinfdevolucioncompras", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.ObtieneURLinfDevolucionCompras))))
	http.HandleFunc("/obtieneurlinfreimpresionrecepcionoc", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.ObtieneURLinfReimpresionRecepcionoc))))
	http.HandleFunc("/obtieneurlinfcomprasporfamilia", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.ObtieneURLinfComprasPorFamilia))))
	http.HandleFunc("/geturladministracionsolicpac", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.GetURLAdministracionSolicPac))))
	http.HandleFunc("/geturldispensarsolicpac", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.GetURLDispensarSolicPac))))
	http.HandleFunc("/geturladministracionsolicbod", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.GetURLAdministracionSolicBod))))
	http.HandleFunc("/geturldespacharsolicbod", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.GetURLDespacharSolicBod))))
	http.HandleFunc("/geturlrecepcionarsolicbod", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.GetURLRecepcionarSolicBod))))
	http.HandleFunc("/geturldevolversolicbod", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.GetURLDevolverSolicBod))))
	http.HandleFunc("/geturlrecepdevolsolicbod", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.GetURLRecepDevolSolicBod))))
	http.HandleFunc("/geturlstocklibcontrolados", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.GetURLStockLibControlados))))
	http.HandleFunc("/geturlconsultalibcontrolados", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.GetURLConsultaLibControlados))))
	http.HandleFunc("/geturlconsultarecetaprog", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.GetURLConsultaRecetaProg))))
	http.HandleFunc("/geturlmovimientos", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.GetURLMovimientos))))
	http.HandleFunc("/geturlstockdebodega", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.GetURLStockdeBodega))))
	http.HandleFunc("/geturlstockcierrekardex", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.GetURLStockCierreKardex))))
	http.HandleFunc("/geturlconsultacierrekardex", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.GetURLConsultaCierreKardex))))
	http.HandleFunc("/geturldespachoreceta", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.GetURLDespachoReceta))))
	http.HandleFunc("/getversionrest", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.GetVersionrest))))
	http.HandleFunc("/geturlcontrolstockmin", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.GetURLControlStockMin))))
	http.HandleFunc("/geturlplantillas", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.GetURLPlantillas))))
	http.HandleFunc("/geturlsolicitudconsumo", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.GetURLSolicitudConsumo))))
	http.HandleFunc("/geturlpanelintegracionerp", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.GetURLPanelIntegracionERP))))
	http.HandleFunc("/geturlreportepedidogastoservicio", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.GetURLReportePedidoGastoServicio))))
	http.HandleFunc("/geturlrptimprimerecetaanulada", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.GetRPTImprimeRecetaAnulada))))
	http.HandleFunc("/geturlrptimprimerecetaanuladatotal", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.GetURLImprimeRecetaAnuladaTotal))))
	http.HandleFunc("/geturlreporterecetasgeneradas", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.GetURLReporteRecetasGeneradas))))
	http.HandleFunc("/geturlreporterecepcionentrebodegas", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.GetURLReporteRecepcionEntreBodegas))))
	http.HandleFunc("/geturlreporteprestamos", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.GetURLReportePrestamos))))
	http.HandleFunc("/obtieneurlconteomanualinventario", mdw.PanicRecovery(tipoLogger, mdw.Preflight((controller.GetURLReporteConteoManualInventario))))

	// Modulos de Servicios Rest
	http.HandleFunc("/listatipobodega", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.Listatipobodega))))
	http.HandleFunc("/listatipoproducto", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.Listatipoproducto))))
	http.HandleFunc("/listartiporelacionbodegas", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.Listartiporelacionbodegas))))
	http.HandleFunc("/principioactivo", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.PrincipioActivo))))
	http.HandleFunc("/presentacion", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.Presentacion))))
	http.HandleFunc("/formafarma", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.FormaFarma))))
	http.HandleFunc("/unidaddecompra", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.UnidadDeCompra))))
	http.HandleFunc("/unidaddedespacho", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.UnidadDeDespacho))))
	http.HandleFunc("/familia", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.Familia))))
	http.HandleFunc("/subfamilia", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.SubFamilia))))
	http.HandleFunc("/tipomedicamento", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.TipoMedicamento))))
	http.HandleFunc("/prioridades", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.Prioridades))))
	http.HandleFunc("/formadepago", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.FormaDePago))))
	http.HandleFunc("/estadoordendecompra", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.EstadoOrdenDeCompra))))
	http.HandleFunc("/tipoderegistro", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.TipoDeRegistro))))
	http.HandleFunc("/buscaholding", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.BuscaHolding))))
	http.HandleFunc("/buscaempresa", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.BuscaEmpresa))))
	http.HandleFunc("/buscasucursal", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.BuscaSucursal))))
	http.HandleFunc("/validausuario", mdw.PanicRecovery(tipoLogger, mdw.Preflight(controller.ValidaUsuario)))
	http.HandleFunc("/periodos", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.Periodos))))
	http.HandleFunc("/tipodoctomercantil", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.TipoDoctoMercantil))))
	http.HandleFunc("/tipodocumentoident", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.TipoDocumentoIdent))))
	http.HandleFunc("/tipomotivocargo", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.TipoMotivoCargo))))
	http.HandleFunc("/tipodespacho", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.TipoDespacho))))
	http.HandleFunc("/periodosinventarios", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.PeriodosInventarios))))
	http.HandleFunc("/tiposdeajustesinv", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.TiposDeAjustesInv))))
	http.HandleFunc("/buscausuarios", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.BuscaUsuarios))))
	http.HandleFunc("/bodegas", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.Bodegas))))
	http.HandleFunc("/llenaestadossolbod", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.LlenaEstadosSolBod))))
	http.HandleFunc("/bodegascargo", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.BodegasCargo))))
	http.HandleFunc("/bodegasdestino", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.BodegasDestino))))
	http.HandleFunc("/traeciudades", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.TraeCiudades))))
	http.HandleFunc("/traecomunas", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.TraeComunas))))
	http.HandleFunc("/bodegasparaasignar", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.BodegasParaAsignar))))
	http.HandleFunc("/traebodegasxservicios", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.TraeBodegasXServicios))))
	http.HandleFunc("/servicios", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.Servicios))))
	http.HandleFunc("/serviciosconbodegas", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.ServiciosConBodegas))))
	http.HandleFunc("/bodegasperifericas", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.BodegasPerifericas))))
	http.HandleFunc("/bodegasdespachadoras", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.BodegasDespachadoras))))
	http.HandleFunc("/facturaelectronica", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.FacturaElectronica))))
	http.HandleFunc("/estadoproveedor", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.EstadoProveedor))))
	http.HandleFunc("/tipoambito", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.TipoAmbito))))
	http.HandleFunc("/tiporeceta", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.TipoReceta))))
	http.HandleFunc("/estadosolicitud", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.EstadoSolicitud))))
	http.HandleFunc("/docidentificacion", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.DocIdentificacion))))
	http.HandleFunc("/traeclinservicios", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.TraeClinServicios))))
	http.HandleFunc("/buscasolicituddet", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.BuscaSolicitudDet))))
	http.HandleFunc("/buscareglasservicios", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.BuscaReglasServicios))))
	http.HandleFunc("/buscareglas", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.BuscaReglas))))
	http.HandleFunc("/buscasolicitudescabecera", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.BuscaSolicitudesCabecera))))
	http.HandleFunc("/buscasolicitudes", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.BuscaSolicitudes))))
	http.HandleFunc("/grabarsolicitudes", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.GrabarSolicitudesTrans))))
	http.HandleFunc("/buscaplantillas", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.BuscaPlantillas))))
	http.HandleFunc("/grabarplantillas", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.GrabarPlantillas))))
	http.HandleFunc("/despachosolicitudbodega", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.DespachoSolicitudBodega))))
	http.HandleFunc("/despacharautopedido", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.DespacharAutopedido))))
	http.HandleFunc("/productosdespachoautopedido", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.ProductosDespachoAutopedido))))
	http.HandleFunc("/devolverautopedido", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.DevolverAutopedido))))
	http.HandleFunc("/dispensarpaciente", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.DispensarPacienteTrans))))
	http.HandleFunc("/recepciondevolucionpaciente", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.RecepcionDevolucionPacienteTrans))))
	http.HandleFunc("/grabadevoluciones", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.GrabaDevoluciones))))
	http.HandleFunc("/cerrarsolicitud", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.CerrarSolicitud))))
	http.HandleFunc("/buscaprodporcodigo", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.BuscaProdPorCodigo))))
	http.HandleFunc("/buscarproductos", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.BuscarProductos))))
	http.HandleFunc("/buscaprodpordescripcion", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.BuscaProdPorDescripcion))))
	http.HandleFunc("/buscaprodportipo", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.BuscaProdporTipo))))
	http.HandleFunc("/buscaprodporprincipio", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.BuscaProdporPrincipio))))
	http.HandleFunc("/grabamedicamento", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.GrabaMedicamento))))
	http.HandleFunc("/actualizamedicamento", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.ActualizaMedicamento))))
	http.HandleFunc("/eliminamedicamento", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.EliminaMedicamento))))
	http.HandleFunc("/grabacheckmedicamento", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.GrabarCheckMedicamento))))
	http.HandleFunc("/grababodega", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.GrabaBodega))))
	http.HandleFunc("/validabodega", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.ValidaBodega))))
	http.HandleFunc("/asociaservicioabodega", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.AsociaServicioaBodega))))
	http.HandleFunc("/estadovigentebodega", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.EstadoVigenteBodega))))
	http.HandleFunc("/estadonovigentebodega", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.EstadoNoVigenteBodega))))
	http.HandleFunc("/productosxbodega", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.ProductosxBodega))))
	http.HandleFunc("/asignaproductosabodega", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.AsignaProductosaBodega))))
	http.HandleFunc("/eliminarproductosabod", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.EliminarProductosaBod))))
	http.HandleFunc("/prodadistribuir", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.ProdaDistribuir))))
	http.HandleFunc("/productounitario", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.ProductoUnitario))))
	http.HandleFunc("/nuevosproductounitario", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.NuevosProductoUnitario))))
	http.HandleFunc("/grabafraccionados", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.GrabaFraccionados))))
	http.HandleFunc("/eliminafraccionados", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.EliminaFraccionados))))
	http.HandleFunc("/encabezadomovfarmacia", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.EncabezadoMovFarmacia))))
	http.HandleFunc("/validacodigomame", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.ValidaCodigoMame))))
	http.HandleFunc("/resbuscaxcodigodesc", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.ResBuscaxCodigoDesc))))
	http.HandleFunc("/consultadevol", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.ConsultaDevol))))
	http.HandleFunc("/consultatodasdevol", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.ConsultaTodasDevol))))
	http.HandleFunc("/grabarencabrecadomov", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.GrabarEncabRecadoMov))))
	http.HandleFunc("/grabardetallemov", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.GrabarDetalleMov))))
	http.HandleFunc("/grabarmovdevolucion", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.GrabarMovDevolucion))))
	http.HandleFunc("/grabarmovimientos", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.GrabarMovimientos))))
	http.HandleFunc("/grabarmovimientosdevol", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.GrabarMovimientosDevol))))
	http.HandleFunc("/buscamovimientos", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.BuscaMovimientos))))
	http.HandleFunc("/generainventario", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.GeneraInventario))))
	http.HandleFunc("/ConsultaInventario", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.ConsultaInventario))))
	http.HandleFunc("/autorizaConteoInvenario", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.AutorizaConteoInvenario))))
	http.HandleFunc("/grabarinvmanual", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.GrabarInvManual))))
	http.HandleFunc("/actualizainv", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.ActualizaInv))))
	http.HandleFunc("/grabaajustes", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.GrabaAjustes))))
	http.HandleFunc("/buscastockenbodegas", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.BuscaStockenBodegas))))
	http.HandleFunc("/grabaajustesstock", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.GrabaAjustesStock))))
	http.HandleFunc("/buscaajustestockegas", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.BuscaAjusteStockegas))))
	http.HandleFunc("/buscavaloresmamein", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.BuscaValoresMamein))))
	http.HandleFunc("/buscaajustevalores", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.BuscaAjusteValores))))
	http.HandleFunc("/movimientoskardex", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.MovimientosKardex))))
	http.HandleFunc("/buscadatoskardex", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.BuscaDatosKardex))))
	http.HandleFunc("/buscaordendecompra", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.BuscaOrdendeCompra))))
	http.HandleFunc("/buscadoctosasococ", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.BuscaDoctosAsocOC))))
	http.HandleFunc("/buscadetalleoc", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.BuscaDetalleOC))))
	http.HandleFunc("/buscaordenesdecompra", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.BuscaOrdenesdeCompra))))
	http.HandleFunc("/reimprimiroc", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.ReimprimirOC))))
	http.HandleFunc("/ocvaloranterior", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.OCValorAnterior))))
	http.HandleFunc("/ocproveedor", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.OCProveedor))))
	http.HandleFunc("/detalleguiaoc", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.DetalleGuiaOC))))
	http.HandleFunc("/rescataguia", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.RescataGuia))))
	http.HandleFunc("/cerrarordendecompra", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.CerrarOrdendeCompra))))
	http.HandleFunc("/valorcostoanterior", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.ValorCostoAnterior))))
	http.HandleFunc("/grabarencabezadooc", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.GrabarEncabezadoOC))))
	http.HandleFunc("/grabardetalleoc", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.GrabarDetalleOC))))
	http.HandleFunc("/imprimiroc", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.ImprimirOC))))
	http.HandleFunc("/datoscabeceraoc", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.DatosCabeceraOC))))
	http.HandleFunc("/datosdetalleocdevo", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.DatosDetalleOCDevo))))
	http.HandleFunc("/detalleocdevo", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.DetalleOCDevo))))
	http.HandleFunc("/grabadevolucionesoc", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.GrabaDevolucionesOC))))
	http.HandleFunc("/buscaporrut", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.BuscaPorRut))))
	http.HandleFunc("/buscapornombre", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.BuscaPorNombre))))
	http.HandleFunc("/buscapacienteambito", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.BuscaPacienteAmbito))))
	http.HandleFunc("/buscapaciente", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.BuscaPaciente))))
	http.HandleFunc("/buscaproveedorporrut", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.BuscaProveedorporRut))))
	http.HandleFunc("/buscaproveedorpornombre", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.BuscaProveedorporNombre))))
	http.HandleFunc("/productosxproveedor", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.ProductosxProveedor))))
	http.HandleFunc("/grabarprovemein", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.GrabarProveMein))))
	http.HandleFunc("/eliminarprovemein", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.EliminarProveMein))))
	http.HandleFunc("/grabarproveedor", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.GrabarProveedor))))
	http.HandleFunc("/modificarproveedor", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.ModificarProveedor))))

	http.HandleFunc("/buscatraspasos", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.BuscaTraspasos))))
	http.HandleFunc("/llenatraspaso", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.LlenaTraspaso))))
	http.HandleFunc("/llenadetatraspaso", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.LlenaDetaTraspaso))))
	http.HandleFunc("/buscastock", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.BuscaStock))))
	http.HandleFunc("/grabartraspasos", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.GrabarTraspasos))))
	http.HandleFunc("/grabardetalletraspasos", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.GrabarDetalleTraspasos))))
	http.HandleFunc("/grabarencabsolicitudbod", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.GrabarEncabSolicitudBod))))
	http.HandleFunc("/retornaencsolicitudbod", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.RetornaEncSolicitudBod))))
	http.HandleFunc("/grabardetasolicitudbod", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.GrabarDetaSolicitudBod))))
	http.HandleFunc("/retornadetsolicitudbod", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.RetornaDetSolicitudBod))))
	http.HandleFunc("/retconsultaencsolicitudbod", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.RetConsultaEncSolicitudBod))))
	http.HandleFunc("/obtenerprivilegios", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.ObtenerPrivilegios))))
	http.HandleFunc("/registrosparareposicion", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.RegistrosParaReposicion))))
	http.HandleFunc("/solobodegasperifericas", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.SoloBodegasPerifericas))))
	http.HandleFunc("/grabasolicitudrepo", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.GrabaSolicitudRepo))))
	http.HandleFunc("/seleventosolicitud", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.SelEventoSolicitud))))
	http.HandleFunc("/selorigensolicitud", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.SelOrigenSolicitud))))
	http.HandleFunc("/seldeteventosolicitud", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.SelDetEventoSolicitud))))
	http.HandleFunc("/selbodegasolicitante", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.SelBodegaSolicitante))))
	http.HandleFunc("/selbodegadespachareceta", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.SelBodegaDespachaReceta))))
	http.HandleFunc("/selbodegasuministro", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.SelBodegaSuministro))))
	http.HandleFunc("/selsuministroaorigen", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.SelSuministroaOrigen))))
	http.HandleFunc("/listaunidades", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.ListaUnidades))))
	http.HandleFunc("/listaservicios", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.ListaServicios))))
	http.HandleFunc("/listapiezas", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.ListaPiezas))))
	http.HandleFunc("/listacamas", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.ListaCamas))))
	http.HandleFunc("/recepciondespachobodega", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.RecepcionDespachoBodega))))
	http.HandleFunc("/recepciondevolucionbodega", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.RecepcionDevolucionBodega))))
	http.HandleFunc("/selvia", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.SelVia))))
	http.HandleFunc("/movimientosfarmacia", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.MovimientosFarmacia))))
	http.HandleFunc("/solicitudespacienteproducto", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.SolicitudesPacienteProducto))))
	http.HandleFunc("/productosdespachobodega", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.ProductosDespachoBodega))))
	http.HandleFunc("/productosrecepcionbodega", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.ProductosRecepcionBodega))))
	http.HandleFunc("/productosrecepcionbodegatotal", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.ProductosRecepcionBodegaTotal))))
	http.HandleFunc("/productosdevolucionbodega", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.ProductosDevolucionBodega))))
	http.HandleFunc("/boxtiporeposicion", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.BoxTipoReposicion))))
	http.HandleFunc("/selstockcritico", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.SelStockCritico))))
	http.HandleFunc("/productosafraccionar", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.ProductosaFraccionar))))
	http.HandleFunc("/productosfraccionados", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.ProductosFraccionados))))
	http.HandleFunc("/lotesdelprodpac", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.LotesDelProdPac))))
	http.HandleFunc("/validacantdevuelvepac", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.ValidaCantDevuelvePac))))
	http.HandleFunc("/tipomovimientofarmacia", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.TipoMovimientoFarmacia))))
	http.HandleFunc("/lotesdelproddespachar", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.LotesDelProdDespachar))))
	http.HandleFunc("/recepciondevolucionpac", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.RecepcionDevolucionPac))))
	http.HandleFunc("/desasociaservicioabodega", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.DesasociaServicioaBodega))))
	http.HandleFunc("/desasociausuarioabodega", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.DesasociaUsuarioaBodega))))
	http.HandleFunc("/desasociarelacionbodega", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.DesasociaRelacionBodega))))
	http.HandleFunc("/desasociaproductobodega", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.DesasociaProductoBodega))))
	http.HandleFunc("/buscarcabecerabodegas", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.BuscarCabeceraBodegas))))
	http.HandleFunc("/buscarEstructuraBodegas", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.BuscarEstructuraBodegas))))
	http.HandleFunc("/ListaEstructuraServicioBodegas", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.ListaEstructuraServicioBodegas))))
	http.HandleFunc("/grabarestructurabodega", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.GrabarEstructuraBodega))))
	http.HandleFunc("/grabarmovimientosfarmacia", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.GrabarMovimientosFarmacia))))
	http.HandleFunc("/lotesdelprodbod", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.LotesDelProdBod))))
	http.HandleFunc("/validacantdevuelvebod", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.ValidaCantDevuelveBod))))
	http.HandleFunc("/lotesdelproddispensar", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.LotesDelProdDispensar))))
	http.HandleFunc("/getsaldolotesbodega", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.GetSaldoLotesBodega))))
	http.HandleFunc("/getversion", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.GetVersion))))
	http.HandleFunc("/creaajustestockmanual", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.CreaAjusteStockManual))))
	http.HandleFunc("/buscabodegacontrolstockminimo", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.BuscaBodegaControlStockMinimo))))
	http.HandleFunc("/bodegascontrolados", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.BodegasControlados))))
	http.HandleFunc("/selbodinvmedcontrolados", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.SelBodInvMedControlados))))
	http.HandleFunc("/creacierrelibromedcontrolados", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.CreaCierreLibroMedControladosTrans))))
	http.HandleFunc("/selperimedcontrolados", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.SelPeriMedControlados))))
	http.HandleFunc("/selcierrelibromedcontrolados", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.SelCierreLibroMedControlados))))
	http.HandleFunc("/seldiasentregarecetaprog", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.SelDiasEntregaRecetaProg))))
	http.HandleFunc("/selconsultarecetaprog", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.SelConsultaRecetaProg))))
	http.HandleFunc("/buscarrecetasficha", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.BuscarRecetasFicha))))
	http.HandleFunc("/buscarrecetasfichamonitor", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.BuscarRecetasFichaMonitor))))
	http.HandleFunc("/buscarestructurarecetas", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.BuscarEstructuraRecetas))))
	http.HandleFunc("/buscarCentroCostoUsuarios", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.BuscarCentroCostoUsuarios))))
	http.HandleFunc("/guardarCentroCostoUsuarios", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.GuardarCentroCostoUsuarios))))
	http.HandleFunc("/guardarRolesUsuarios", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.GuardarRolesUsuarios))))
	http.HandleFunc("/buscarRolesUsuarios", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.BuscarRolesUsuarios))))
	http.HandleFunc("/buscarRoles", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.BuscarRoles))))
	http.HandleFunc("/selcierrekardexbodinv", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.SelCierreKardexBodInv))))
	http.HandleFunc("/creacierrekardexbodega", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.CreaCierreKardexBodega))))
	http.HandleFunc("/selperiodoscierrekardex", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.SelPeriodosCierreKardex))))
	http.HandleFunc("/selcierrekardexprodbod", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.SelCierreKardexProdBod))))
	http.HandleFunc("/buscarLotedetalleplantilla", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.BuscarLoteDetallePlantilla))))
	http.HandleFunc("/buscaplantillascabecera", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.BuscaPlantillasCabecera))))
	http.HandleFunc("/selbodegafraccionable", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.SelBodegaFraccionable))))
	http.HandleFunc("/selConsultaFraccionamiento", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.SelConsultaFraccionamiento))))
	http.HandleFunc("/buscarestructurarecetasmodal", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.BuscarEstructuraRecetasModal))))
	http.HandleFunc("/buscasolicitudescabeceramonitor", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.BuscaSolicitudCabeceraMonitor))))
	http.HandleFunc("/servicioporbodega", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.ServiciosPorBodega))))
	http.HandleFunc("/combobodegadevpac", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.ComboBodegaDevPac))))
	http.HandleFunc("/listatipooperacion", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.ListaTipoOperacion))))

	http.HandleFunc("/filtrosolicitudbodega", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.FiltroSolicitudBodega))))
	http.HandleFunc("/devolucionfraccionado", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.DevolucionFraccionado))))
	http.HandleFunc("/anulaciondespachobodega", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.AnulacionDespachoBodega))))
	http.HandleFunc("/devolverdispensacioncuentapaciente", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.DevolverDispensacionCuentaPacienteTrans))))
	http.HandleFunc("/buscasolicitudesdevolpac", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.BuscaSolicitudesDevolPac))))
	http.HandleFunc("/combotiporechazo", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.ComboTipoRechazo))))
	http.HandleFunc("/interfazsolicitudesacentrales", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.InterfazSolicitudesaCentrales))))
	http.HandleFunc("/recedevolpacrechazo", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.ReceDevolPacRechazoTrans))))
	http.HandleFunc("/validausuariorechazo", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.ValidaUsuarioRechazo))))
	http.HandleFunc("/obtenermantencion", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.ObtenerMantencion))))
	http.HandleFunc("/wsconsultasaldo", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.WsConsultaSaldo))))
	http.HandleFunc("/consultacargopacientebod", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.ConsultaCargoPacienteBod))))
	http.HandleFunc("/modestadosolicitud", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.ModEstadoSolicitud))))

	http.HandleFunc("/selestadostraspasosfin700", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.SelEstadoTraspasosFin700))))
	http.HandleFunc("/generareceta", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.GeneraReceta))))
	http.HandleFunc("/buscaprofesional", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.BuscaProfesional))))
	http.HandleFunc("/buscastockbodegas", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.BuscaStockBodegas))))
	http.HandleFunc("/confirmagrabarsolicitudes", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.ConfirmaGrabarSolicitudes))))
	http.HandleFunc("/tipopedidoplantillabodega", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.TipoPedidoPlantillaBodega))))
	http.HandleFunc("/buscalotes", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.BuscaLotes))))
	http.HandleFunc("/buscaprodporlote", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.BuscaProdPorLote))))
	http.HandleFunc("/consultaproductolotes", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.ConsultaProductoLotes))))
	http.HandleFunc("/consultaconsumolotes", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.ConsultaConsumoLotes))))
	http.HandleFunc("/consultabodegalotes", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.ConsultaBodegaLotes))))
	http.HandleFunc("/confirmastockbodsuministro", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.ConfirmaStockBodSuministro))))
	http.HandleFunc("/geturlsolicitudautopedido", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.GetURLSolicitudAutopedido))))
	http.HandleFunc("/obtenerlistacobromedicamento", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.ObtenerListaCobroMedicamento))))
	http.HandleFunc("/grabarfactorconversionproducto", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.GrabarFactorConversionProducto))))
	http.HandleFunc("/eliminareceta", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.EliminaReceta))))
	http.HandleFunc("/solicitudespendiente", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.SolicitudesPendiente))))

	http.HandleFunc("/anulardispensacionreceta", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.AnularDispensacionReceta))))
	http.HandleFunc("/listaanulardispensacionreceta", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.ListaAnularDispensacionReceta))))

	// Mantenedor de parametros
	http.HandleFunc("/buscartipoparametros", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.BuscarTipoParametros))))
	http.HandleFunc("/buscarparametros", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.BuscarParametros))))
	http.HandleFunc("/grabarparametros", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.GrabarParametros))))

	// Mantenedor de reglas
	http.HandleFunc("/buscarserviciosmantenedordereglas", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.BuscarServiciosMantenedorDeReglas))))
	http.HandleFunc("/buscabodegasmantenedorreglas", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.BuscaBodegasMantenedorDeReglas))))
	http.HandleFunc("/buscareglasporcodigoservicio", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.BuscaReglasPorCodigodeServicio))))
	http.HandleFunc("/grabarreglasdeservicio", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.GrabarReglasDeServicio))))

	http.HandleFunc("/configUserMulti", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.ConfigUserMulti))))
	http.HandleFunc("/clasificacionProducto", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.ClasificacionProducto))))

	// Informacion de versiones
	// Informacion general del logistico,
	http.HandleFunc("/informaciongeneral", mdw.PanicRecovery(tipoLogger, mdw.Preflight(controller.InformacionGeneral)))

	// Configuracion del logistico general, pero solo si esta logueado
	http.HandleFunc("/configuracionlogistico", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.Configuracionlogistico))))

	http.HandleFunc("/buscaprodporcodigoprov", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.BuscaProdPorCodigoProv))))

	// Prestamos
	http.HandleFunc("/consularparaminitprestamos", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.ConsularParamInitPrestamos))))
	http.HandleFunc("/buscarprestamos", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.BuscarPrestamos))))
	http.HandleFunc("/crearprestamo", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.CrearPrestamo))))
	http.HandleFunc("/forzarcierreprestamo", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.ForzarCierrePrestamo))))

	//Informe Lista Conteo Inventario
	http.HandleFunc("/filtroinformelistaconteoinventario", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.FiltroInformeListaConteoInventario))))
	http.HandleFunc("/filtrogenerarajusteinventario", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.FiltroGenerarAjusteInventario))))
	http.HandleFunc("/filtroinventariovalorizado", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.FiltroInventarioValorizado))))
	http.HandleFunc("/filtrogenerarinventariosistemas", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.FiltroGenerarInventarioSistemas))))
	http.HandleFunc("/periodosgenerarajusteinventarios", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.PeriodosGenerarAjusteInventarios))))
	http.HandleFunc("/periodosinventariovalorizado", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.PeriodosInventarioValorizado))))

	http.HandleFunc("/crearnuevoconteo", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.CrearNuevoConteo))))
	http.HandleFunc("/crearnuevomotivoinventario", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.CrearMotivoAjusteInventario))))
	http.HandleFunc("/crearnuevoajusteinventario", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.CrearNuevoAjusteInventario))))
	http.HandleFunc("/obtenerultimoperiodoinventario", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.ObtenerUltimoPeriodoInventario))))
	http.HandleFunc("/gestionarperiodoinventario", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.GestionarPeriodoInventario))))
	http.HandleFunc("/bloquearbodegasinventario", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.BloquearBodegasInventario))))
	http.HandleFunc("/cargarbodegasinventario", mdw.PanicRecovery(tipoLogger, mdw.Preflight(mdw.Autenticacion(controller.CargarBodegasInventario))))

	http.HandleFunc("/hi", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprintf(w, "Hi")
	})

	// LEVANTAR SERVIDOR
	msgInicioServicios := "Inicio de main.go en http://localhost:8091"
	log.Println(msgInicioServicios)
	logger.Info(logs.InformacionLog{Mensaje: msgInicioServicios})

	log.Fatal(http.ListenAndServe(":8091", nil))
}
