DROP TABLE "FARMACIACLINICA"."CLIN_FAR_MAMEIN_CHECK";
  CREATE TABLE "FARMACIACLINICA"."CLIN_FAR_MAMEIN_CHECK" 
   (	
    "MEINCHK_ID" NUMBER(10,0) DEFAULT CLIN_FAR_MAMEIN_CHECK_SEQ.nextval NOT NULL,
	"MEINCHK_PRODUCTO_STOCK" NUMBER(1) DEFAULT 0,
	"MEINCHK_VIGENTE" NUMBER(1) DEFAULT 0,    
    "MEINCHK_CONSUMO_RESTRINGIDO" NUMBER(1) DEFAULT 0,
    "MEINCHK_REPO_AUTO" NUMBER(1) DEFAULT 0,
    "MEINCHK_FECHA_VENC" NUMBER(1) DEFAULT 0,
    "MEINCHK_MAGISTRAL" NUMBER(1) DEFAULT 0,
    "MEINCHK_VALOR_VAR" NUMBER(1) DEFAULT 0,
    "MEINCHK_POS" NUMBER(1) DEFAULT 0,
    "MEINCHK_POSS" NUMBER(1) DEFAULT 0,
    "MEINCHK_CONSUMO_GENERAL" NUMBER(1) DEFAULT 0,
    "MEINCHK_PRECIO_REGULADO" NUMBER(1) DEFAULT 0,
    "MEINCHK_ACONDICIONAMIENTO" NUMBER(1) DEFAULT 0,
    "MEINCHK_ADECUADO" NUMBER(1) DEFAULT 0,
    "MEINCHK_ART_INS_ESPECIAL" NUMBER(1) DEFAULT 0,    	
	"MEIN_CODMEI" VARCHAR2(25) NOT NULL,
    PRIMARY KEY (MEINCHK_ID)
   );
   
CREATE SEQUENCE "FARMACIACLINICA"."CLIN_FAR_MAMEIN_CHECK_SEQ" START WITH 1;   