
  CREATE TABLE "FARMACIACLINICA"."CLIN_FAR_PROGRAMACION_GUIA_PEDIDO" 
   (	"PROG_ID" NUMBER NOT NULL ENABLE, 
	"PROG_HDGCODIGO" NUMBER NOT NULL ENABLE, 
	"PROG_ESACODIGO" NUMBER NOT NULL ENABLE, 
	"PROG_CMECODIGO" NUMBER NOT NULL ENABLE, 
	"PROG_DIA" NUMBER NOT NULL ENABLE, 
	"PROG_DIAGLOSA" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"PROG_PRODVALOR" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"PROG_PRODCODIGO" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"PROG_PRODDESC" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	 CONSTRAINT "CLIN_FAR_PROGRAMACION_GUIA_PEDIDO_PK" PRIMARY KEY ("PROG_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FARMACIACLINICA_DATA"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FARMACIACLINICA_DATA" ;
/
   CREATE SEQUENCE  "FARMACIACLINICA"."PROGRAMACION_GUIA_PEDIDO_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
/