
  CREATE TABLE "FARMACIACLINICA"."CLIN_FAR_OC_LOG" 
   (	"OCLG_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"OCLG_ORCO_ID" NUMBER(10,0), 
	"OCLG_ESTADO_OLD" NUMBER(6,0), 
	"OCLG_ESTADO_NEW" NUMBER(6,0), 
	"OCLG_PROV_ID_OLD" NUMBER(10,0), 
	"OCLG_PROV_ID_NEW" NUMBER(10,0), 
	"OCLG_USER" VARCHAR2(20 BYTE), 
	"OCLG_FECHA" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FARMACIACLINICA_DATA" ;