CREATE TABLE CLIN_FAR_PARAM_EVENTOS (
    EVENTO_ID   NUMBER(9, 0) GENERATED ALWAYS AS IDENTITY,
    FPAR_ID     NUMBER(6, 0),
    DESCRIPCION VARCHAR2(4000 CHAR) NOT NULL,
    USUARIO     VARCHAR2(20 CHAR) NOT NULL,
    TIPO_EVENTO VARCHAR2(1 CHAR) NOT NULL,
    FECHA       DATE DEFAULT SYSDATE NOT NULL,

    CONSTRAINT PK_CLIN_FAR_PARAM_EVENTOS PRIMARY KEY ( EVENTO_ID ),
    FOREIGN KEY ( FPAR_ID ) REFERENCES CLIN_FAR_PARAM ( FPAR_ID ) ON DELETE SET NULL,
    CONSTRAINT CLIN_FAR_PARAM_EVENTOS_DESCRIPCION_ES_JSON CHECK ( DESCRIPCION IS JSON ),
    CONSTRAINT CLIN_FAR_PARAM_EVENTOS_EVENTO_VALIDO CHECK ( TIPO_EVENTO IN ( 'C', 'M' ) )
);

COMMENT ON TABLE "FARMACIACLINICA"."CLIN_FAR_PARAM_EVENTOS" IS 'Tabla de eventos asociados a los cambios en la tabla CLIN_FAR_PARAM';
COMMENT ON COLUMN "FARMACIACLINICA"."CLIN_FAR_PARAM_EVENTOS"."EVENTO_ID" IS 'ID del evento. No hay que especificarlo al momento de insertar una fila, se autoincrementa solo';
COMMENT ON COLUMN "FARMACIACLINICA"."CLIN_FAR_PARAM_EVENTOS"."FPAR_ID" IS 'ID del parametro en tabla CLIN_FAR_PARAM asociado a este evento. Si es NULL es porque el parametro fue eliminada';
COMMENT ON COLUMN "FARMACIACLINICA"."CLIN_FAR_PARAM_EVENTOS"."DESCRIPCION" IS 'JSON con los cambios realizados al parametro';
COMMENT ON COLUMN "FARMACIACLINICA"."CLIN_FAR_PARAM_EVENTOS"."USUARIO" IS 'Nombre del usuario que realizó los cambios';
COMMENT ON COLUMN "FARMACIACLINICA"."CLIN_FAR_PARAM_EVENTOS"."TIPO_EVENTO" IS '"C" = se creo el parametro; "M" = se modifico el parametro';
COMMENT ON COLUMN "FARMACIACLINICA"."CLIN_FAR_PARAM_EVENTOS"."FECHA" IS 'Instante de cuando ocurrio el evento. No es necesario especificarlo al momento de crear un evento';

/
