  CREATE TABLE "FARMACIACLINICA"."RPT_RECETASANULADASCAB" 
   (	"IDREPORT" NUMBER(12,0) NOT NULL ENABLE, 
	"SOLIID" NUMBER(12,0), 
	"RECEID" NUMBER(12,0), 
	"FECHACREACION" VARCHAR2(20 BYTE), 
	"GLSTIPIDENTIFICACION" VARCHAR2(50 BYTE), 
	"NUMDOCPAC" VARCHAR2(20 BYTE), 
	"GLSSEXO" VARCHAR2(50 BYTE), 
	"CTANUMCUENTA" NUMBER(10,0), 
	"NOMBREPAC" VARCHAR2(210 BYTE), 
	"EDAD" VARCHAR2(25 BYTE), 
	"CAMGLOSA" VARCHAR2(100 BYTE), 
	"GLSAMBITO" VARCHAR2(50 BYTE), 
	"ESTADOSOLICITUDDE" VARCHAR2(50 BYTE), 
	"UNDGLOSA" VARCHAR2(100 BYTE), 
	"PZAGLOSA" VARCHAR2(100 BYTE), 
	"NOMBREMEDICO" VARCHAR2(100 BYTE), 
	"BODORIGENDESC" VARCHAR2(50 BYTE), 
	"BODDESTINODESC" VARCHAR2(50 BYTE), 
	"BODORIGEN" NUMBER(3,0), 
	"BODDESTINO" NUMBER(3,0), 
	"TIPOREG" CHAR(1 BYTE), 
	"HDGCODIGO" NUMBER(8,0), 
	"ESACODIGO" NUMBER(8,0), 
	"CMECODIGO" NUMBER(8,0), 
	"FECHARPT" DATE, 
	"USUARIOANULA" VARCHAR2(100 BYTE), 
	"FECHAANULACION" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 1 NEXT 1 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FARMACIACLINICA_DATA" ;
/

  CREATE TABLE "FARMACIACLINICA"."RPT_RECETASANULADASDET" 
   (	"IDREPORT" NUMBER(12,0) NOT NULL ENABLE, 
	"SOLIID" NUMBER(12,0), 
	"RECEID" NUMBER(12,0), 
	"CODMEI" VARCHAR2(10 BYTE), 
	"MEINDESCRI" VARCHAR2(100 BYTE), 
	"LOTE" VARCHAR2(50 BYTE) DEFAULT ( ' ' ),
	"DOSIS" NUMBER(10,0), 
	"FORMULACION" NUMBER(10,0), 
	"DIAS" NUMBER(10,0), 
	"CANTSOLI" NUMBER(10,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 0 NEXT 1 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FARMACIACLINICA_DATA" ;
