DROP TABLE "FARMACIACLINICA"."RPT_ORDENCOMPRA";
  CREATE TABLE "FARMACIACLINICA"."RPT_ORDENCOMPRA" 
   (	"IDREPORT" NUMBER(12,0),
	"RPT_OC_CLI_RUT" VARCHAR2(30),
	"RPT_OC_CLI_DIR" VARCHAR2(30),
	"RPT_OC_CLI_COMU" VARCHAR2(30),
	"RPT_OC_CLI_FONO" NUMBER(10,0),
	"RPT_OC_PROV_RESP" VARCHAR2(30),
	"RPT_OC_PROV_DIR" VARCHAR2(30),
	"RPT_OC_PROV_COMU" VARCHAR2(30),
	"RPT_OC_PROV_FONO" NUMBER(12,0),
	"RPT_OC_PROV_RUT" VARCHAR2(30),
	"RPT_OC_PROV_CIUDAD" VARCHAR2(30),
	"RPT_OC_MEIN_COD" NUMBER(12,0),
	"RPT_OC_MEIN_NOMBRE" VARCHAR2(30),
	"RPT_OC_MEIN_CANT" NUMBER(12,0),
	"RPT_OC_MEIN_COSTO" NUMBER(12,0),
	"RPT_OC_MEIN_TOTAL" NUMBER(12,0)
   );