DROP TABLE "FARMACIACLINICA"."RPT_RECEPCION_SOLICITUDES_ENTRE_BODEGAS";

CREATE TABLE "FARMACIACLINICA"."RPT_RECEPCION_SOLICITUDES_ENTRE_BODEGAS" (
    ID_REPORTE            NUMBER(12, 0),
    SOLICITUD_ID          NUMBER(12, 0),
    HDGCODIGO             NUMBER(8, 0),
    ESACODIGO             NUMBER(8, 0),
    CMECODIGO             NUMBER(8, 0),
    ESTADO_SOLICITUD      VARCHAR2(50 BYTE),
    BODEGA_SOLICITANTE    VARCHAR2(50 BYTE),
    BODEGA_DESPACHO       VARCHAR2(50 BYTE),
    CODMEI                VARCHAR2(10 BYTE),
    NOMBRE_PRODUCTO       VARCHAR2(100 BYTE),
    CANTIDAD_SOLICITADA   NUMBER(10, 0),
    CANT_DESPACHADA       NUMBER(10, 0),
    CANTIDAD_RECEPCIONADA NUMBER(10, 0),
    FECHA_RECEPCION       DATE,
    HORA_RECEPCION        VARCHAR(10),
    USUARIO_RECEPCIONA    VARCHAR2(60 BYTE),
    LOTE                  VARCHAR2(20 BYTE),
    FECHA_VENCIMIENTO     DATE,
    FECHA_REPORTE         DATE
);