Insert into CLIN_FAR_PARAM 
(FPAR_TIPO,FPAR_CODIGO,FPAR_DESCRIPCION,FPAR_ESTADO,FPAR_USERNAME,FPAR_FECHA_CREACION,FPAR_MODIFICABLE,FPAR_INCLUYE_CODIGO,FPAR_VALOR,FPAR_HDGCODIGO,FPAR_ESACODIGO,FPAR_CMECODIGO) 
values ('111','1','Nacido vivo','0','SONDA',to_date('11/09/2023 12:00:00AM','DD/MM/RRRR HH:MI:SSAM'),'N',null,'Nacido vivo','2','10','57');

Insert into CLIN_FAR_PARAM 
(FPAR_TIPO,FPAR_CODIGO,FPAR_DESCRIPCION,FPAR_ESTADO,FPAR_USERNAME,FPAR_FECHA_CREACION,FPAR_MODIFICABLE,FPAR_INCLUYE_CODIGO,FPAR_VALOR,FPAR_HDGCODIGO,FPAR_ESACODIGO,FPAR_CMECODIGO) 
values ('111','2','Registro Civil','0','SONDA',to_date('11/09/2023 12:00:00AM','DD/MM/RRRR HH:MI:SSAM'),'N',null,'Registro Civil','2','10','57');

Insert into CLIN_FAR_PARAM 
(FPAR_TIPO,FPAR_CODIGO,FPAR_DESCRIPCION,FPAR_ESTADO,FPAR_USERNAME,FPAR_FECHA_CREACION,FPAR_MODIFICABLE,FPAR_INCLUYE_CODIGO,FPAR_VALOR,FPAR_HDGCODIGO,FPAR_ESACODIGO,FPAR_CMECODIGO) 
values ('111','3','Tarjeta de Identidad','0','SONDA',to_date('11/09/2023 12:00:00AM','DD/MM/RRRR HH:MI:SSAM'),'N',null,'Tarjeta de Identidad','2','10','57');

Insert into CLIN_FAR_PARAM 
(FPAR_TIPO,FPAR_CODIGO,FPAR_DESCRIPCION,FPAR_ESTADO,FPAR_USERNAME,FPAR_FECHA_CREACION,FPAR_MODIFICABLE,FPAR_INCLUYE_CODIGO,FPAR_VALOR,FPAR_HDGCODIGO,FPAR_ESACODIGO,FPAR_CMECODIGO) 
values ('111','4','Cedula de Ciudadania','0','SONDA',to_date('11/09/2023 12:00:00AM','DD/MM/RRRR HH:MI:SSAM'),'N',null,'Cedula de Ciudadania','2','10','57');

Insert into CLIN_FAR_PARAM 
(FPAR_TIPO,FPAR_CODIGO,FPAR_DESCRIPCION,FPAR_ESTADO,FPAR_USERNAME,FPAR_FECHA_CREACION,FPAR_MODIFICABLE,FPAR_INCLUYE_CODIGO,FPAR_VALOR,FPAR_HDGCODIGO,FPAR_ESACODIGO,FPAR_CMECODIGO) 
values ('111','5','Pasaporte','0','SONDA',to_date('11/09/2023 12:00:00AM','DD/MM/RRRR HH:MI:SSAM'),'N',null,'Cedula de Ciudadania','2','10','57');
-- Medico
Insert into CLIN_FAR_PARAM 
(FPAR_TIPO,FPAR_CODIGO,FPAR_DESCRIPCION,FPAR_ESTADO,FPAR_USERNAME,FPAR_FECHA_CREACION,FPAR_MODIFICABLE,FPAR_INCLUYE_CODIGO,FPAR_VALOR,FPAR_HDGCODIGO,FPAR_ESACODIGO,FPAR_CMECODIGO) 
values ('112','1','Cedula de Ciudadania','0','SONDA',to_date('11/09/2023 12:00:00AM','DD/MM/RRRR HH:MI:SSAM'),'N',null,'Cedula de Ciudadania','2','10','57');

Insert into CLIN_FAR_PARAM 
(FPAR_TIPO,FPAR_CODIGO,FPAR_DESCRIPCION,FPAR_ESTADO,FPAR_USERNAME,FPAR_FECHA_CREACION,FPAR_MODIFICABLE,FPAR_INCLUYE_CODIGO,FPAR_VALOR,FPAR_HDGCODIGO,FPAR_ESACODIGO,FPAR_CMECODIGO) 
values ('112','2','Registro Medico','0','SONDA',to_date('11/09/2023 12:00:00AM','DD/MM/RRRR HH:MI:SSAM'),'N',null,'Registro Medico','2','10','57');

COMMIT;