/
Insert into FARMACIACLINICA.CLIN_FAR_ROLES (ID_ROL,HDGCODIGO,ESACODIGO,CMECODIGO,CODIGO_ROL,NOMBRE_ROL,DESCRIPCION_ROL) values ('19000','1','2','1','19000','Consulta Kardex','Ingresa a la pantalla de consulta de Kardex');
/
Insert into FARMACIACLINICA.CLIN_FAR_ROLES (ID_ROL,HDGCODIGO,ESACODIGO,CMECODIGO,CODIGO_ROL,NOMBRE_ROL,DESCRIPCION_ROL) values ('19000','1','3','2','19000','Consulta Kardex','Ingresa a la pantalla de consulta de Kardex');
/
Insert into FARMACIACLINICA.CLIN_FAR_ROLES (ID_ROL,HDGCODIGO,ESACODIGO,CMECODIGO,CODIGO_ROL,NOMBRE_ROL,DESCRIPCION_ROL) values ('19000','1','5','1','19000','Consulta Kardex','Ingresa a la pantalla de consulta de Kardex');
/
Insert into FARMACIACLINICA.CLIN_FAR_ROLES (ID_ROL,HDGCODIGO,ESACODIGO,CMECODIGO,CODIGO_ROL,NOMBRE_ROL,DESCRIPCION_ROL) values ('19000','1','8','3','19000','Consulta Kardex','Ingresa a la pantalla de consulta de Kardex');
/

Insert into FARMACIACLINICA.CLIN_FAR_ROLES_OPCIONES (ID_ROL,ID_OPCION,HDGCODIGO,ESACODIGO,CMECODIGO) values ('19000','300000','1','2','1');
/
Insert into FARMACIACLINICA.CLIN_FAR_ROLES_OPCIONES (ID_ROL,ID_OPCION,HDGCODIGO,ESACODIGO,CMECODIGO) values ('19000','300000','1','3','2');
/
Insert into FARMACIACLINICA.CLIN_FAR_ROLES_OPCIONES (ID_ROL,ID_OPCION,HDGCODIGO,ESACODIGO,CMECODIGO) values ('19000','300000','1','8','3');
/
Insert into FARMACIACLINICA.CLIN_FAR_ROLES_OPCIONES (ID_ROL,ID_OPCION,HDGCODIGO,ESACODIGO,CMECODIGO) values ('19000','370000','1','2','1');
/
Insert into FARMACIACLINICA.CLIN_FAR_ROLES_OPCIONES (ID_ROL,ID_OPCION,HDGCODIGO,ESACODIGO,CMECODIGO) values ('19000','370000','1','3','2');
/
Insert into FARMACIACLINICA.CLIN_FAR_ROLES_OPCIONES (ID_ROL,ID_OPCION,HDGCODIGO,ESACODIGO,CMECODIGO) values ('19000','370000','1','8','3');
/
Insert into FARMACIACLINICA.CLIN_FAR_ROLES_OPCIONES (ID_ROL,ID_OPCION,HDGCODIGO,ESACODIGO,CMECODIGO) values ('19000','372000','1','2','1');
/
Insert into FARMACIACLINICA.CLIN_FAR_ROLES_OPCIONES (ID_ROL,ID_OPCION,HDGCODIGO,ESACODIGO,CMECODIGO) values ('19000','372000','1','3','2');
/
Insert into FARMACIACLINICA.CLIN_FAR_ROLES_OPCIONES (ID_ROL,ID_OPCION,HDGCODIGO,ESACODIGO,CMECODIGO) values ('19000','372000','1','8','3');
/
Insert into FARMACIACLINICA.CLIN_FAR_ROLES_OPCIONES (ID_ROL,ID_OPCION,HDGCODIGO,ESACODIGO,CMECODIGO) values ('19000','372100','1','2','1');
/
Insert into FARMACIACLINICA.CLIN_FAR_ROLES_OPCIONES (ID_ROL,ID_OPCION,HDGCODIGO,ESACODIGO,CMECODIGO) values ('19000','372100','1','3','2');
/
Insert into FARMACIACLINICA.CLIN_FAR_ROLES_OPCIONES (ID_ROL,ID_OPCION,HDGCODIGO,ESACODIGO,CMECODIGO) values ('19000','372100','1','8','3');
/
Insert into FARMACIACLINICA.CLIN_FAR_ROLES_OPCIONES (ID_ROL,ID_OPCION,HDGCODIGO,ESACODIGO,CMECODIGO) values ('19000','372200','1','2','1');
/
Insert into FARMACIACLINICA.CLIN_FAR_ROLES_OPCIONES (ID_ROL,ID_OPCION,HDGCODIGO,ESACODIGO,CMECODIGO) values ('19000','372200','1','3','2');
/
Insert into FARMACIACLINICA.CLIN_FAR_ROLES_OPCIONES (ID_ROL,ID_OPCION,HDGCODIGO,ESACODIGO,CMECODIGO) values ('19000','372200','1','8','3');
/