INSERT INTO "FARMACIACLINICA"."CLIN_FAR_MAMEIN_CLASIFICACION" (MEINCLASS_CLASE, MEINCLASS_DESCRIPCION) VALUES ('I(A)', 'Riesgo Bajo Instrumental quirúrgicos/gasa');
INSERT INTO "FARMACIACLINICA"."CLIN_FAR_MAMEIN_CLASIFICACION" (MEINCLASS_CLASE, MEINCLASS_DESCRIPCION) VALUES ('IIA (B)', 'Riesgo Moderado	Agujas hipodérmicas/equipo de succión');
INSERT INTO "FARMACIACLINICA"."CLIN_FAR_MAMEIN_CLASIFICACION" (MEINCLASS_CLASE, MEINCLASS_DESCRIPCION) VALUES ('IIB ©', 'Riesgo Alto Ventilador pulmonar/ implantes ortopédicos');
INSERT INTO "FARMACIACLINICA"."CLIN_FAR_MAMEIN_CLASIFICACION" (MEINCLASS_CLASE, MEINCLASS_DESCRIPCION) VALUES ('III (D)', 'Riesgo Muy Alto	Válvulas cardiacas / marcapasos');
INSERT INTO "FARMACIACLINICA"."CLIN_FAR_MAMEIN_CLASIFICACION" (MEINCLASS_CLASE, MEINCLASS_DESCRIPCION) VALUES ('SIN INFORMACION', 'Riesgo no definido');
COMMIT;