-- URL Web Services Fin700
Insert into CLIN_FAR_PARAM (FPAR_ID,FPAR_TIPO,FPAR_CODIGO,FPAR_DESCRIPCION,FPAR_ESTADO,FPAR_USERNAME,FPAR_FECHA_CREACION,FPAR_MODIFICABLE,FPAR_INCLUYE_CODIGO,FPAR_VALOR) values ('1197','80','0','URL utilizada en Interfaz.go','0','SICIFAR',to_date('02/12/20','DD/MM/RR'),'N',null,'0');
/
Insert into CLIN_FAR_PARAM (FPAR_ID,FPAR_TIPO,FPAR_CODIGO,FPAR_DESCRIPCION,FPAR_ESTADO,FPAR_USERNAME,FPAR_FECHA_CREACION,FPAR_MODIFICABLE,FPAR_INCLUYE_CODIGO,FPAR_VALOR) values ('1193','80','1','URL PUBLICA wsLogIntegraOperacion funcion enviarmovimientosFin700Masivo (0: Activo / 1: Inactivo)','0','SICIFAR',to_date('02/12/20','DD/MM/RR'),'N',null,'http://10.211.30.25/fin700testws/wsLogIntegraOperacion/wsLogIntegraOperacion.asmx?wsdl');
/
Insert into CLIN_FAR_PARAM (FPAR_ID,FPAR_TIPO,FPAR_CODIGO,FPAR_DESCRIPCION,FPAR_ESTADO,FPAR_USERNAME,FPAR_FECHA_CREACION,FPAR_MODIFICABLE,FPAR_INCLUYE_CODIGO,FPAR_VALOR) values ('1194','80','1','URL PRIVADA wsLogIntegraOperacion funcion enviarmovimientosFin700Masivo (0: Activo / 1: Inactivo)','1','SICIFAR',to_date('02/12/20','DD/MM/RR'),'N',null,'http://10.211.30.25/fin700testws/wsLogIntegraOperacion/wsLogIntegraOperacion.asmx?wsdl');
/
Insert into CLIN_FAR_PARAM (FPAR_ID,FPAR_TIPO,FPAR_CODIGO,FPAR_DESCRIPCION,FPAR_ESTADO,FPAR_USERNAME,FPAR_FECHA_CREACION,FPAR_MODIFICABLE,FPAR_INCLUYE_CODIGO,FPAR_VALOR) values ('1195','80','2','URL PRIVADA wsLogIntegraPedido funcion dispensacionRecetalegado  (0: Activo / 1: Inactivo)','1','SICIFAR',to_date('02/12/20','DD/MM/RR'),'N',null,'http://128.10.55.236:8082/services/farmacia?wsdl');
/
Insert into CLIN_FAR_PARAM (FPAR_ID,FPAR_TIPO,FPAR_CODIGO,FPAR_DESCRIPCION,FPAR_ESTADO,FPAR_USERNAME,FPAR_FECHA_CREACION,FPAR_MODIFICABLE,FPAR_INCLUYE_CODIGO,FPAR_VALOR) values ('1196','80','2','URL PUBLICA wsLogIntegraPedido funcion dispensacionRecetalegado (0: Activo / 1: Inactivo)','0','SICIFAR',to_date('02/12/20','DD/MM/RR'),'N',null,'http://128.10.55.236:8082/services/farmacia?wsdl');
/
Insert into CLIN_FAR_PARAM (FPAR_ID,FPAR_TIPO,FPAR_CODIGO,FPAR_DESCRIPCION,FPAR_ESTADO,FPAR_USERNAME,FPAR_FECHA_CREACION,FPAR_MODIFICABLE,FPAR_INCLUYE_CODIGO,FPAR_VALOR) values ('1198','80','3','URL PUBLICA wsLogIntegraPedido funcion wsLogIntegraPedido (0: Activo / 1: Inactivo)','0','SICIFAR',to_date('02/12/20','DD/MM/RR'),'N',null,'http://10.211.30.25/fin700testws/wsLogIntegraPedido/wsLogIntegraPedido.asmx?WSDL');
/
Insert into CLIN_FAR_PARAM (FPAR_ID,FPAR_TIPO,FPAR_CODIGO,FPAR_DESCRIPCION,FPAR_ESTADO,FPAR_USERNAME,FPAR_FECHA_CREACION,FPAR_MODIFICABLE,FPAR_INCLUYE_CODIGO,FPAR_VALOR) values ('1199','80','3','URL PRIVADA wsLogIntegraPedido funcion wsLogIntegraPedido  (0: Activo / 1: Inactivo)','1','SICIFAR',to_date('02/12/20','DD/MM/RR'),'N',null,'http://10.211.30.25/fin700testws/wsLogIntegraPedido/wsLogIntegraPedido.asmx?WSDL');
/
Insert into CLIN_FAR_PARAM (FPAR_ID,FPAR_TIPO,FPAR_CODIGO,FPAR_DESCRIPCION,FPAR_ESTADO,FPAR_USERNAME,FPAR_FECHA_CREACION,FPAR_MODIFICABLE,FPAR_INCLUYE_CODIGO,FPAR_VALOR) values ('1225','80','4','URL PUBLICA WmConsultaSaldo funcion WmConsultaSaldo (0: Activo / 1: Inactivo)','0','SICIFAR',to_date('01/03/20','DD/MM/RR'),'N',null,'http://10.211.30.25/fin700testws/wsLogIntegraConsulta/wsLogIntegraConsulta.asmx?WSDL');
/
Insert into CLIN_FAR_PARAM (FPAR_ID,FPAR_TIPO,FPAR_CODIGO,FPAR_DESCRIPCION,FPAR_ESTADO,FPAR_USERNAME,FPAR_FECHA_CREACION,FPAR_MODIFICABLE,FPAR_INCLUYE_CODIGO,FPAR_VALOR) values ('1226','80','4','URL PUBLICA WmConsultaSaldo funcion WmConsultaSaldo (0: Activo / 1: Inactivo)','1','SICIFAR',to_date('01/03/20','DD/MM/RR'),'N',null,'http://10.211.30.25/fin700testws/wsLogIntegraConsulta/wsLogIntegraConsulta.asmx?WSDL');