CREATE OR REPLACE EDITIONABLE SYNONYM "FARMACIACLINICA"."UNIDADCENTRO" FOR "DESA2"."UNIDADCENTRO";
/
CREATE OR REPLACE EDITIONABLE SYNONYM "FARMACIACLINICA"."CAMA" FOR "DESA2"."CAMA";
/
CREATE OR REPLACE EDITIONABLE SYNONYM "FARMACIACLINICA"."CAMADEF" FOR "DESA2"."CAMADEF";
/
CREATE OR REPLACE EDITIONABLE SYNONYM "FARMACIACLINICA"."CARGOCUENTA" FOR "DESA2"."CARGOCUENTA";
/
CREATE OR REPLACE EDITIONABLE SYNONYM "FARMACIACLINICA"."CENTROMEDICO" FOR "DESA2"."CENTROMEDICO";
/
CREATE OR REPLACE EDITIONABLE SYNONYM "FARMACIACLINICA"."CLIENTE" FOR "DESA2"."CLIENTE";
/
CREATE OR REPLACE EDITIONABLE SYNONYM "FARMACIACLINICA"."COMPROBANTEINGRESO" FOR "DESA2"."COMPROBANTEINGRESO";
/
CREATE OR REPLACE EDITIONABLE SYNONYM "FARMACIACLINICA"."CONFIGURACIONCONEXION" FOR "DESA2"."CONFIGURACIONCONEXION";
/
CREATE OR REPLACE EDITIONABLE SYNONYM "FARMACIACLINICA"."CUENTA" FOR "DESA2"."CUENTA";
/
CREATE OR REPLACE EDITIONABLE SYNONYM "FARMACIACLINICA"."CUENTAPLANPACRSC" FOR "DESA2"."CUENTAPLANPACRSC";
/
CREATE OR REPLACE EDITIONABLE SYNONYM "FARMACIACLINICA"."EMPRESA" FOR "DESA2"."EMPRESA";
/
CREATE OR REPLACE EDITIONABLE SYNONYM "FARMACIACLINICA"."ESPECIALIDADPROF" FOR "DESA2"."ESPECIALIDADPROF";
/
CREATE OR REPLACE EDITIONABLE SYNONYM "FARMACIACLINICA"."ESTADIA" FOR "DESA2"."ESTADIA";
/
CREATE OR REPLACE EDITIONABLE SYNONYM "FARMACIACLINICA"."ESTADIAPLANPACRSC" FOR "DESA2"."ESTADIAPLANPACRSC";
/
CREATE OR REPLACE EDITIONABLE SYNONYM "FARMACIACLINICA"."HOLDING" FOR "DESA2"."HOLDING";
/
CREATE OR REPLACE EDITIONABLE SYNONYM "FARMACIACLINICA"."PACIENTE" FOR "DESA2"."PACIENTE";
/
CREATE OR REPLACE EDITIONABLE SYNONYM "FARMACIACLINICA"."PIEZA" FOR "DESA2"."PIEZA";
/
CREATE OR REPLACE EDITIONABLE SYNONYM "FARMACIACLINICA"."PIEZADEF" FOR "DESA2"."PIEZADEF";
/
CREATE OR REPLACE EDITIONABLE SYNONYM "FARMACIACLINICA"."PLANPACIENTERSC" FOR "DESA2"."PLANPACIENTERSC";
/
CREATE OR REPLACE EDITIONABLE SYNONYM "FARMACIACLINICA"."PRMAMBITO" FOR "DESA2"."PRMAMBITO";
/
CREATE OR REPLACE EDITIONABLE SYNONYM "FARMACIACLINICA"."PRMSEXO" FOR "DESA2"."PRMSEXO";
/
CREATE OR REPLACE EDITIONABLE SYNONYM "FARMACIACLINICA"."PRMTIPOIDENTIFICACION" FOR "DESA2"."PRMTIPOIDENTIFICACION";
/
CREATE OR REPLACE EDITIONABLE SYNONYM "FARMACIACLINICA"."PROFESIONAL" FOR "DESA2"."PROFESIONAL";
/
CREATE OR REPLACE EDITIONABLE SYNONYM "FARMACIACLINICA"."SERVICIO" FOR "DESA2"."SERVICIO";
/
CREATE OR REPLACE EDITIONABLE SYNONYM "FARMACIACLINICA"."SERVICIOCENTRO" FOR "DESA2"."SERVICIOCENTRO";
/
CREATE OR REPLACE EDITIONABLE SYNONYM "FARMACIACLINICA"."UNIDAD" FOR "DESA2"."UNIDAD";
/
CREATE OR REPLACE EDITIONABLE SYNONYM "FARMACIACLINICA"."UNIDADCENTRO" FOR "DESA2"."UNIDADCENTRO";
/
-- PRIVADM
CREATE OR REPLACE EDITIONABLE SYNONYM "FARMACIACLINICA"."TBL_USER" FOR "PRIVADM"."TBL_USER";
/
CREATE OR REPLACE EDITIONABLE SYNONYM "FARMACIACLINICA"."TBL_CONTROLCLAVEUSR" FOR "PRIVADM"."TBL_CONTROLCLAVEUSR";
/