CREATE OR REPLACE EDITIONABLE SYNONYM "FARMACIACLINICA"."UNIDADCENTRO" FOR "DESA1"."UNIDADCENTRO";
/
CREATE OR REPLACE EDITIONABLE SYNONYM "FARMACIACLINICA"."CAMA" FOR "DESA1"."CAMA";
/
CREATE OR REPLACE EDITIONABLE SYNONYM "FARMACIACLINICA"."CAMADEF" FOR "DESA1"."CAMADEF";
/
CREATE OR REPLACE EDITIONABLE SYNONYM "FARMACIACLINICA"."CARGOCUENTA" FOR "DESA1"."CARGOCUENTA";
/
CREATE OR REPLACE EDITIONABLE SYNONYM "FARMACIACLINICA"."CENTROMEDICO" FOR "DESA1"."CENTROMEDICO";
/
CREATE OR REPLACE EDITIONABLE SYNONYM "FARMACIACLINICA"."CLIENTE" FOR "DESA1"."CLIENTE";
/
CREATE OR REPLACE EDITIONABLE SYNONYM "FARMACIACLINICA"."COMPROBANTEINGRESO" FOR "DESA1"."COMPROBANTEINGRESO";
/
CREATE OR REPLACE EDITIONABLE SYNONYM "FARMACIACLINICA"."CONFIGURACIONCONEXION" FOR "DESA1"."CONFIGURACIONCONEXION";
/
CREATE OR REPLACE EDITIONABLE SYNONYM "FARMACIACLINICA"."CUENTA" FOR "DESA1"."CUENTA";
/
CREATE OR REPLACE EDITIONABLE SYNONYM "FARMACIACLINICA"."CUENTAPLANPACRSC" FOR "DESA1"."CUENTAPLANPACRSC";
/
CREATE OR REPLACE EDITIONABLE SYNONYM "FARMACIACLINICA"."EMPRESA" FOR "DESA1"."EMPRESA";
/
CREATE OR REPLACE EDITIONABLE SYNONYM "FARMACIACLINICA"."ESPECIALIDADPROF" FOR "DESA1"."ESPECIALIDADPROF";
/
CREATE OR REPLACE EDITIONABLE SYNONYM "FARMACIACLINICA"."ESTADIA" FOR "DESA1"."ESTADIA";
/
CREATE OR REPLACE EDITIONABLE SYNONYM "FARMACIACLINICA"."ESTADIAPLANPACRSC" FOR "DESA1"."ESTADIAPLANPACRSC";
/
CREATE OR REPLACE EDITIONABLE SYNONYM "FARMACIACLINICA"."HOLDING" FOR "DESA1"."HOLDING";
/
CREATE OR REPLACE EDITIONABLE SYNONYM "FARMACIACLINICA"."PACIENTE" FOR "DESA1"."PACIENTE";
/
CREATE OR REPLACE EDITIONABLE SYNONYM "FARMACIACLINICA"."PIEZA" FOR "DESA1"."PIEZA";
/
CREATE OR REPLACE EDITIONABLE SYNONYM "FARMACIACLINICA"."PIEZADEF" FOR "DESA1"."PIEZADEF";
/
CREATE OR REPLACE EDITIONABLE SYNONYM "FARMACIACLINICA"."PLANPACIENTERSC" FOR "DESA1"."PLANPACIENTERSC";
/
CREATE OR REPLACE EDITIONABLE SYNONYM "FARMACIACLINICA"."PRMAMBITO" FOR "DESA1"."PRMAMBITO";
/
CREATE OR REPLACE EDITIONABLE SYNONYM "FARMACIACLINICA"."PRMSEXO" FOR "DESA1"."PRMSEXO";
/
CREATE OR REPLACE EDITIONABLE SYNONYM "FARMACIACLINICA"."PRMTIPOIDENTIFICACION" FOR "DESA1"."PRMTIPOIDENTIFICACION";
/
CREATE OR REPLACE EDITIONABLE SYNONYM "FARMACIACLINICA"."PROFESIONAL" FOR "DESA1"."PROFESIONAL";
/
CREATE OR REPLACE EDITIONABLE SYNONYM "FARMACIACLINICA"."SERVICIO" FOR "DESA1"."SERVICIO";
/
CREATE OR REPLACE EDITIONABLE SYNONYM "FARMACIACLINICA"."SERVICIOCENTRO" FOR "DESA1"."SERVICIOCENTRO";
/
CREATE OR REPLACE EDITIONABLE SYNONYM "FARMACIACLINICA"."UNIDAD" FOR "DESA1"."UNIDAD";
/
CREATE OR REPLACE EDITIONABLE SYNONYM "FARMACIACLINICA"."UNIDADCENTRO" FOR "DESA1"."UNIDADCENTRO";
/
-- PRIVADM
CREATE OR REPLACE EDITIONABLE SYNONYM "FARMACIACLINICA"."TBL_USER" FOR "PRIVADM"."TBL_USER";
/
CREATE OR REPLACE EDITIONABLE SYNONYM "FARMACIACLINICA"."TBL_CONTROLCLAVEUSR" FOR "PRIVADM"."TBL_CONTROLCLAVEUSR";
/