GRANT SELECT ON UNIDADCENTRO TO FARMACIACLINICA; --UNIDADCENTRO;
/
GRANT SELECT ON CAMA TO FARMACIACLINICA; --CAMA;
/
GRANT SELECT ON CAMADEF TO FARMACIACLINICA; --CAMADEF;
/
GRANT SELECT ON CARGOCUENTA TO FARMACIACLINICA; --CARGOCUENTA;
/
GRANT SELECT ON CENTROMEDICO TO FARMACIACLINICA; --CENTROMEDICO;
/
GRANT SELECT ON CLIENTE TO FARMACIACLINICA; --CLIENTE;
/
GRANT SELECT ON COMPROBANTEINGRESO TO FARMACIACLINICA; --COMPROBANTEINGRESO;
/
GRANT SELECT ON CONFIGURACIONCONEXION TO FARMACIACLINICA; --CONFIGURACIONCONEXION;
/
GRANT SELECT ON CUENTA TO FARMACIACLINICA; --CUENTA;
/
GRANT SELECT ON CUENTAPLANPACRSC TO FARMACIACLINICA; --CUENTAPLANPACRSC;
/
GRANT SELECT ON EMPRESA TO FARMACIACLINICA; --EMPRESA;
/
GRANT SELECT ON ESPECIALIDADPROF TO FARMACIACLINICA; --ESPECIALIDADPROF;
/
GRANT SELECT ON ESTADIA TO FARMACIACLINICA; --ESTADIA;
/
GRANT SELECT ON ESTADIAPLANPACRSC TO FARMACIACLINICA; --ESTADIAPLANPACRSC;
/
GRANT SELECT ON HOLDING TO FARMACIACLINICA; --HOLDING;
/
GRANT SELECT ON PACIENTE TO FARMACIACLINICA; --PACIENTE;
/
GRANT SELECT ON PIEZA TO FARMACIACLINICA; --PIEZA;
/
GRANT SELECT ON PIEZADEF TO FARMACIACLINICA; --PIEZADEF;
/
GRANT SELECT ON PLANPACIENTERSC TO FARMACIACLINICA; --PLANPACIENTERSC;
/
GRANT SELECT ON PRMAMBITO TO FARMACIACLINICA; --TO FARMACIACLINICA; --PRMAMBITO;
/
GRANT SELECT ON PRMSEXO TO FARMACIACLINICA; --PRMSEXO;
/
GRANT SELECT ON PRMTIPOIDENTIFICACION TO FARMACIACLINICA; --PRMTIPOIDENTIFICACION;
/
GRANT SELECT ON PROFESIONAL TO FARMACIACLINICA; --PROFESIONAL;
/
GRANT SELECT ON SERVICIO TO FARMACIACLINICA; --SERVICIO;
/
GRANT SELECT ON SERVICIOCENTRO TO FARMACIACLINICA; --SERVICIOCENTRO;
/
GRANT SELECT ON UNIDAD TO FARMACIACLINICA; --UNIDAD;
/
GRANT SELECT ON UNIDADCENTRO TO FARMACIACLINICA; --UNIDADCENTRO;
/
-- PRIVADM
GRANT SELECT ON TBL_USER TO FARMACIACLINICA; --TBL_USER;
/
GRANT SELECT ON TBL_CONTROLCLAVEUSR TO FARMACIACLINICA; --TBL_CONTROLCLAVEUSR