
-- EJECUTAR EN PRIVADM
GRANT SELECT ON TBL_CONTROLCLAVEUSR TO FARMACIACLINICA;
/
-- AJECUTAR EN FARMACIACLINICA
CREATE OR REPLACE EDITIONABLE SYNONYM "FARMACIACLINICA"."TBL_CONTROLCLAVEUSR" FOR "PRIVADM"."TBL_CONTROLCLAVEUSR";
/
