create or replace PACKAGE PKG_FILTRO_SOLICITUD_BODEGA as
    PROCEDURE P_FILTRO_SOLICITUD_BODEGA_CODMEI(
		IN_COD_FILTRO IN VARCHAR2,
		IN_COD_MEI IN VARCHAR2,
        OUT_CURSOR IN OUT SYS_REFCURSOR
    );

	PROCEDURE P_FILTRO_SOLICITUD_BODEGA_PRODCOD(
		IN_COD_FILTRO IN VARCHAR2,
		IN_COD_MEI IN VARCHAR2,
        OUT_CURSOR IN OUT SYS_REFCURSOR
	);
END PKG_FILTRO_SOLICITUD_BODEGA;
/
create or replace PACKAGE BODY PKG_FILTRO_SOLICITUD_BODEGA AS

    PROCEDURE P_FILTRO_SOLICITUD_BODEGA_CODMEI(
		IN_COD_FILTRO IN VARCHAR2,
		IN_COD_MEI IN VARCHAR2,
        OUT_CURSOR IN OUT SYS_REFCURSOR
    ) AS
        SRV_QUERY VARCHAR2(6000);
    BEGIN
		SRV_QUERY := 'select MEIN_CODMEI from clin_far_mamein ' ||
			' where MEIN_CODMEI in (' || IN_COD_FILTRO || ') ' ||
			' and MEIN_CODMEI like ''%' || IN_COD_MEI || '%''';

		-- NTRACELOG_PKG.graba_log('PKG_FILTRO_SOLICITUD_BODEGA',
		--             'CODMEI'
		--             ,null
		--             ,SRV_QUERY);
        
        OPEN OUT_CURSOR FOR SRV_QUERY;

    END P_FILTRO_SOLICITUD_BODEGA_CODMEI;

	PROCEDURE P_FILTRO_SOLICITUD_BODEGA_PRODCOD(
		IN_COD_FILTRO IN VARCHAR2,
		IN_COD_MEI IN VARCHAR2,
        OUT_CURSOR IN OUT SYS_REFCURSOR
    ) AS
        SRV_QUERY VARCHAR2(6000);
    BEGIN
		SRV_QUERY := 'select PROD_CODIGO from CLIN_FAR_PRODUCTOCONSUMO ' ||
			' where PROD_CODIGO in (' || IN_COD_FILTRO || ') ' ||
			' and PROD_CODIGO like ''%' || IN_COD_MEI || '%''';

		-- NTRACELOG_PKG.graba_log('PKG_FILTRO_SOLICITUD_BODEGA',
		--             'PRODCOD'
		--             ,null
		--             ,SRV_QUERY);
        
        OPEN OUT_CURSOR FOR SRV_QUERY;

    END P_FILTRO_SOLICITUD_BODEGA_PRODCOD;
END PKG_FILTRO_SOLICITUD_BODEGA;
/
