create or replace PACKAGE PKG_IMPRIMIR_OC as
    PROCEDURE P_IMPRIMIR_OC(
		IN_ORCO_ID IN NUMBER
    );
END PKG_IMPRIMIR_OC;
/
create or replace PACKAGE BODY PKG_IMPRIMIR_OC AS

    PROCEDURE P_IMPRIMIR_OC(
		IN_ORCO_ID IN NUMBER
    ) AS
    BEGIN
		Update Clin_far_oc SET ORCO_ESTADO = 2, ORCO_FECHA_CIERRE = SYSDATE where ORCO_ID = IN_ORCO_ID;
    END P_IMPRIMIR_OC;
END PKG_IMPRIMIR_OC;
/
