create or replace PACKAGE PKG_GRABA_AJUSTES as
    PROCEDURE P_GRABA_AJUSTES(
		In_Json IN CLOB
    );
END PKG_GRABA_AJUSTES;
/
create or replace PACKAGE BODY PKG_GRABA_AJUSTES AS

    PROCEDURE P_GRABA_AJUSTES(
		In_Json IN CLOB
    ) AS
    BEGIN
		DECLARE 
			NUEVOIDAJUSTE NUMBER;
			INDICE NUMBER;
		BEGIN
			INDICE := 0;
			FOR VJSON IN(
					with json as ( select In_Json doc from dual )  
						SELECT 
							IDDETALLEINVEN
							,IDINVENTARIO
							,IDMEINID
							,CODMEIN
							,STOCKINVENT
							,CONTEOMANUAL
							,VALORCOSTO
							,BODEGAINV
							,RESPONSABLE
							,TIPOMOTIVOAJUS
						FROM  json_table( (select doc from json) , '$[*]' 
							COLUMNS (
									IDDETALLEINVEN   PATH '$.iddetalleinven'
									,IDINVENTARIO    PATH '$.idinventario'
									,IDMEINID PATH '$.idmeinid'
									,CODMEIN   PATH '$.codigomein'
									,STOCKINVENT   PATH '$.stockinvent'
									,CONTEOMANUAL PATH '$.conteomanual'
									,VALORCOSTO   PATH '$.valorcosto'
									,BODEGAINV   PATH '$.bodegainv'
									,RESPONSABLE   PATH '$.responsable'
									,TIPOMOTIVOAJUS   PATH '$.tipomotivoajus'
									)  
					)
				)LOOP
					BEGIN 
						INDICE := INDICE + 1;
						SELECT CLIN_FAR_AJUSTES_SEQ.NEXTVAL INTO NUEVOIDAJUSTE FROM dual;

						INSERT INTO CLIN_FAR_AJUSTES (AJUS_ID, AJUS_FBOD_CODIGO, AJUS_MEIN_ID, AJUS_MEIN_CODMEI, AJUS_STOCK_ANT, AJUS_STOCK_NUE, AJUS_RESPONSABLE, AJUS_FECHA, AJUS_MOTIVO, AJUS_COSTO_UNITARIO ) 
						VALUES (NUEVOIDAJUSTE, VJSON.BODEGAINV, VJSON.IDMEINID, VJSON.CODMEIN, VJSON.STOCKINVENT, VJSON.CONTEOMANUAL, VJSON.RESPONSABLE, sysdate, VJSON.TIPOMOTIVOAJUS, VJSON.VALORCOSTO);
						
						UPDATE CLIN_FAR_INVENTARIOS_DET SET INVD_AJUS_ID = NUEVOIDAJUSTE WHERE INVD_ID = VJSON.IDDETALLEINVEN;

						UPDATE CLIN_FAR_BODEGAS_INV SET FBOI_STOCK_ACTUAL = FBOI_STOCK_ACTUAL + (VJSON.CONTEOMANUAL - VJSON.STOCKINVENT) 
						WHERE FBOI_FBOD_CODIGO = VJSON.BODEGAINV AND FBOI_MEIN_ID = VJSON.IDMEINID;

						IF INDICE = 1 THEN
							UPDATE CLIN_FAR_INVENTARIOS SET INVE_GENERA_AJUSTE = 'S' WHERE INVE_ID = VJSON.IDINVENTARIO;
						END IF;
					END;
				END LOOP;
		END;
    END P_GRABA_AJUSTES;
END PKG_GRABA_AJUSTES;
/
