create or replace PACKAGE PKG_GRABAR_FACTOR_CONVERSION_PRODUCTO as
    PROCEDURE P_GRABAR_FACTOR_CONVERSION_PRODUCTO(
		In_Json IN CLOB,
        IN_HDG_CODIGO IN NUMBER,
		IN_ESA_CODIGO IN NUMBER,
		IN_CME_CODIGO IN NUMBER
    );
END PKG_GRABAR_FACTOR_CONVERSION_PRODUCTO;
/
create or replace PACKAGE BODY PKG_GRABAR_FACTOR_CONVERSION_PRODUCTO AS

    PROCEDURE P_GRABAR_FACTOR_CONVERSION_PRODUCTO(
		In_Json IN CLOB,
        IN_HDG_CODIGO IN NUMBER,
		IN_ESA_CODIGO IN NUMBER,
		IN_CME_CODIGO IN NUMBER
    ) AS        
	 BEGIN
	 	DECLARE
			STRVAL1 NUMBER;

		BEGIN
			FOR VJSON IN(
				with json as (select In_Json doc from dual)  
				SELECT 
					MEINIDORIG
					, MEINIDDEST
					, FACTORCONV
				FROM  json_table( (select doc from json) , '$[*]' 
					COLUMNS (
						MEINIDORIG   PATH '$.meinidorig'
						, MEINIDDEST PATH '$.meiniddest'
						, FACTORCONV PATH '$.factorconv'
					)  
				)
			)LOOP
				BEGIN
					SELECT COUNT(*) 
					INTO STRVAL1
					FROM  CLIN_FAR_DISTRIB_COMPRAS 
					WHERE DCOM_MEIN_ID_ORIGEN  = VJSON.MEINIDORIG
					AND   DCOM_MEIN_ID_DESTINO = VJSON.MEINIDDEST;

					IF STRVAL1 = 0 THEN
						INSERT INTO CLIN_FAR_DISTRIB_COMPRAS 
							(DCOM_MEIN_ID_ORIGEN, 
							DCOM_MEIN_ID_DESTINO, 
							DCOM_FACTOR_CONVERSION, 
							DCOM_VIGENTE, HDGCODIGO, ESACODIGO, CMECODIGO) 
						VALUES (VJSON.MEINIDORIG, 
							VJSON.MEINIDDEST, 
							VJSON.FACTORCONV, 
							'S',
                            IN_HDG_CODIGO,
                            IN_ESA_CODIGO,
                            IN_CME_CODIGO); 
						
						ELSE 
							UPDATE CLIN_FAR_DISTRIB_COMPRAS  
							SET DCOM_FACTOR_CONVERSION =  VJSON.FACTORCONV
							WHERE 
								DCOM_MEIN_ID_ORIGEN =  VJSON.MEINIDORIG
								AND DCOM_MEIN_ID_DESTINO = VJSON.MEINIDDEST
                                AND HDGCODIGO=IN_HDG_CODIGO
                                AND ESACODIGO=IN_ESA_CODIGO
                                AND CMECODIGO=IN_CME_CODIGO; 
					END IF;
				END;
			END LOOP;
		END;
    END P_GRABAR_FACTOR_CONVERSION_PRODUCTO;
END PKG_GRABAR_FACTOR_CONVERSION_PRODUCTO;
/