create or replace PACKAGE PKG_GRABA_DEVOLUCIONES_OC as
    PROCEDURE P_GRABA_DEVOLUCIONES_OC(
		In_Json IN CLOB
    );

END PKG_GRABA_DEVOLUCIONES_OC;
/
create or replace PACKAGE BODY PKG_GRABA_DEVOLUCIONES_OC AS

    PROCEDURE P_GRABA_DEVOLUCIONES_OC(
		In_Json IN CLOB
    ) AS
    BEGIN
		DECLARE 
			STOCKACTUAL NUMBER;
			ORCOID NUMBER;
		BEGIN
			FOR VJSON IN(
					with json as ( select In_Json doc from dual )  
						SELECT 
							OCCANTADEVOL
							,OCDETMOVID
							,OCDETMEINID
							,OCDETMFDEID
							,OCDETNRODOCTO
							,RESPONSABLE
							,OCHDGCODIGO
							,OCESACODIGO
							,OCCMECODIGO
						FROM  json_table( (select doc from json) , '$[*]' 
							COLUMNS (
									OCCANTADEVOL   PATH '$.occantadevol'
									,OCDETMOVID    PATH '$.ocdetmovid'
									,OCDETMEINID   PATH '$.ocdetmeinid'
									,OCDETMFDEID   PATH '$.ocdetmfdeid'
									,OCDETNRODOCTO PATH '$.ocdetnrodocto'
									,RESPONSABLE   PATH '$.responsable'
									,OCHDGCODIGO   PATH '$.ochdgcodigo'
									,OCESACODIGO   PATH '$.ocesacodigo'
									,OCCMECODIGO   PATH '$.occmecodigo'
									)  
					)
				)LOOP
					BEGIN 
						select TraerStockActual(VJSON.OCDETMEINID, VJSON.OCHDGCODIGO, VJSON.OCESACODIGO, VJSON.OCCMECODIGO) INTO STOCKACTUAL from dual;
						IF STOCKACTUAL > VJSON.OCCANTADEVOL THEN
							INSERT INTO CLIN_FAR_OC_DETMOV_DEV( ODMD_ODMO_ID, ODMD_FECHA, ODMD_CANTIDAD, ODMD_RESPONSABLE, ODMD_NOTA_CREDITO ) 
							VALUES (VJSON.OCDETMOVID, SYSDATE, VJSON.OCCANTADEVOL, VJSON.RESPONSABLE, VJSON.OCDETNRODOCTO);
						END IF;

						UPDATE CLIN_FAR_OC_DETMOV SET ODMO_CANT_DEVUELTA = nvl(ODMO_CANT_DEVUELTA,0) + VJSON.OCCANTADEVOL WHERE ODMO_ID = VJSON.OCDETMOVID;
						
						UPDATE CLIN_FAR_BODEGAS_INV SET FBOI_STOCK_ACTUAL = nvl(FBOI_STOCK_ACTUAL,0) - VJSON.OCCANTADEVOL WHERE FBOI_FBOD_CODIGO = BuscaBodGral(VJSON.OCHDGCODIGO, VJSON.OCESACODIGO, VJSON.OCCMECODIGO) AND FBOI_MEIN_ID = VJSON.OCDETMEINID;

						UPDATE CLIN_FAR_MOVIMDET SET MFDE_CANTIDAD_DEVUELTA = NVL(MFDE_CANTIDAD_DEVUELTA,0) + VJSON.OCCANTADEVOL WHERE MFDE_ID = VJSON.OCDETMFDEID;

						INSERT INTO CLIN_FAR_MOVIM_DEVOL (MDEV_ID, MDEV_MFDE_ID, MDEV_MOVF_TIPO, MDEV_FECHA, MDEV_CANTIDAD, MDEV_RESPONSABLE) 
							VALUES (CLIN_MDEV_SEQ.NEXTVAL, VJSON.OCDETMFDEID, 1, SYSDATE, VJSON.OCCANTADEVOL, VJSON.RESPONSABLE);

						UPDATE CLIN_FAR_OC_DET SET ODET_CANT_DEVUELTA = NVL(ODET_CANT_DEVUELTA,0) + VJSON.OCCANTADEVOL WHERE ODET_ID = VJSON.OCDETMOVID;

						SELECT ODET_ORCO_ID INTO ORCOID from CLIN_FAR_OC_DET Where ODET_ID = VJSON.OCDETMOVID AND ODET_CANT_REAL > (ODET_CANT_DESPACHADA - nvl(ODET_CANT_DEVUELTA,0));

						IF ORCOID > 0 THEN
							UPDATE CLIN_FAR_OC_DET SET ODET_ESTADO = 1 WHERE ODET_ID = VJSON.OCDETMOVID;

							UPDATE CLIN_FAR_OC SET ORCO_ESTADO = 3 WHERE ORCO_ID = ORCOID;
						END IF;
					END;
				END LOOP;
		END;

    END P_GRABA_DEVOLUCIONES_OC;
END PKG_GRABA_DEVOLUCIONES_OC;
/
