create or replace PACKAGE PKG_CERRAR_OC as
    PROCEDURE P_CERRAR_OC(
		NUM_OC IN NUMBER,
        IN_HDGCODIGO IN NUMBER, 
        IN_ESACODIGO IN NUMBER, 
        IN_CMECODIGO IN NUMBER
    );
END PKG_CERRAR_OC;
/
create or replace PACKAGE BODY PKG_CERRAR_OC AS

    PROCEDURE P_CERRAR_OC(
		NUM_OC IN NUMBER,
        IN_HDGCODIGO IN NUMBER, 
        IN_ESACODIGO IN NUMBER, 
        IN_CMECODIGO IN NUMBER
    ) AS
    BEGIN
		UPDATE CLIN_FAR_OC SET ORCO_ESTADO=6, ORCO_FECHA_CIERRE = sysdate
		WHERE orco_numdoc=NUM_OC
          AND HDGCODIGO =IN_HDGCODIGO
          AND ESACODIGO =IN_ESACODIGO
          AND CMECODIGO =IN_CMECODIGO;
        COMMIT;
    END P_CERRAR_OC;
END PKG_CERRAR_OC;
/
