create or replace PACKAGE PKG_GRABAR_PLANTILLA_CONSUMO as
    PROCEDURE P_GRABAR_PLANTILLA_CONSUMO(
		In_Json IN CLOB,
		In_Det_Consumo IN CLOB,
		SECUENCIA IN OUT NUMBER
    );
END PKG_GRABAR_PLANTILLA_CONSUMO;
/
create or replace PACKAGE BODY PKG_GRABAR_PLANTILLA_CONSUMO AS

    PROCEDURE P_GRABAR_PLANTILLA_CONSUMO(
		In_Json IN CLOB,
		In_Det_Consumo IN CLOB,
		SECUENCIA IN OUT NUMBER
    ) AS        
	 BEGIN	
	 	DECLARE
			IN_ACCION VARCHAR2(32767);
			SECUENCIA_DETALLE NUMBER;
			IN_HDG_COD NUMBER;
			IN_ESA_COD NUMBER;
			IN_CME_COD NUMBER;
			IN_CENTRO_CONSUMO NUMBER;
			IN_CENTRO_COSTO NUMBER;
			IN_ID_PRESUPUESTO NUMBER;
			IN_GLOSA VARCHAR2(32767);
			IN_REFERENCIA_CONTABLE NUMBER;
			IN_OPERACION_CONTABLE NUMBER;
			IN_ESTADO NUMBER;
			IN_ID NUMBER;
			SRV_QUERY VARCHAR2(32767);

		BEGIN
			SELECT JSON_VALUE(In_Json, '$.accion') AS IN_ACCION INTO IN_ACCION FROM DUAL;
			SELECT JSON_VALUE(In_Json, '$.hdgcodigo') AS IN_HDG_COD INTO IN_HDG_COD FROM DUAL;
			SELECT JSON_VALUE(In_Json, '$.esacodigo') AS IN_ESA_COD INTO IN_ESA_COD FROM DUAL;
			SELECT JSON_VALUE(In_Json, '$.cmecodigo') AS IN_CME_COD INTO IN_CME_COD FROM DUAL;
			SELECT JSON_VALUE(In_Json, '$.centrocosto') AS IN_CENTRO_COSTO INTO IN_CENTRO_COSTO FROM DUAL;
			SELECT JSON_VALUE(In_Json, '$.idpresupuesto') AS IN_ID_PRESUPUESTO INTO IN_ID_PRESUPUESTO FROM DUAL;
			SELECT JSON_VALUE(In_Json, '$.glosa') AS IN_GLOSA INTO IN_GLOSA FROM DUAL;
			SELECT JSON_VALUE(In_Json, '$.referenciacontable') AS IN_REFERENCIA_CONTABLE INTO IN_REFERENCIA_CONTABLE FROM DUAL;
			SELECT JSON_VALUE(In_Json, '$.operacioncontable') AS IN_OPERACION_CONTABLE INTO IN_OPERACION_CONTABLE FROM DUAL;
			SELECT JSON_VALUE(In_Json, '$.estado') AS IN_ESTADO INTO IN_ESTADO FROM DUAL;
			SELECT JSON_VALUE(In_Json, '$.id') AS IN_ID INTO IN_ID FROM DUAL;

			Select CLIN_PLANTILLACONSUMO_SEQ.NEXTVAL INTO SECUENCIA from dual;

			IF IN_ACCION = 'I' THEN
				insert into CLIN_FAR_PLANTILLACONSUMO  (ID,HDGCODIGO,ESACODIGO,CMECODIGO,CENTROCOSTO,ID_PRESUPUESTO,GLOSA,REFERENCIA_CONTABLE,OPERACION_CONTABLE,ESTADO)
				VALUES (
				SECUENCIA
				, IN_HDG_COD
				, IN_ESA_COD
				, IN_CME_COD
				, IN_CENTRO_COSTO
				, IN_ID_PRESUPUESTO
				, IN_GLOSA
				, IN_REFERENCIA_CONTABLE
				, IN_OPERACION_CONTABLE
				, IN_ESTADO
				);
			END IF;

			IF IN_ACCION = 'M' THEN
				update CLIN_FAR_PLANTILLACONSUMO
				set CENTROCOSTO = IN_CENTRO_COSTO
				, ID_PRESUPUESTO =  IN_ID_PRESUPUESTO
				, GLOSA   = IN_GLOSA
				, REFERENCIA_CONTABLE =  IN_REFERENCIA_CONTABLE
				, OPERACION_CONTABLE =  IN_OPERACION_CONTABLE
				, ESTADO =  IN_ESTADO
				 where ID = IN_ID;
			END IF;

			IF IN_ACCION = 'E' THEN
				delete CLIN_FAR_DETPLANTILLACONSUMO
				where ID = IN_ID;

				delete CLIN_FAR_PLANTILLACONSUMO
				where ID = IN_ID;
			END IF;

			FOR VJSON IN(
                with json as (select In_Det_Consumo doc from dual)  
				SELECT 
					ACCION
					, CENTROCOSTO
					, IDPRESUPUESTO
					, IDPRODUCTO
					, CODIGOPRODUCTO
					, GLOSAPRODUCTO
					, CANTIDADSOLICITADA
					, OPERACIONCONTABLE
					, ESTADO
					, IDDETALLE
				FROM  json_table( (select doc from json) , '$[*]' 
					COLUMNS (
						ACCION               PATH '$.accion'
						, CENTROCOSTO        PATH '$.centrocosto'
						, IDPRESUPUESTO      PATH '$.idpresupuesto'
						, IDPRODUCTO         PATH '$.idproducto'
						, CODIGOPRODUCTO     PATH '$.codigoproducto'
						, GLOSAPRODUCTO      PATH '$.glosaproducto'
						, CANTIDADSOLICITADA PATH '$.cantidadsolicitada'
						, OPERACIONCONTABLE  PATH '$.operacioncontable'
						, ESTADO             PATH '$.estado'
						, IDDETALLE          PATH '$.iddetalle'
					)  
                )
            )LOOP
				BEGIN
					IF VJSON.ACCION = 'I' THEN
						Select CLIN_PLANTILLACONSUMODET_SEQ.NEXTVAL INTO SECUENCIA_DETALLE from dual;

						SRV_QUERY := 'insert into CLIN_FAR_DETPLANTILLACONSUMO (ID_DETAELLE, ID,CENTROCOSTO,ID_PRESUPUESTO,ID_PRODUCTO,CODIGO_PRODUCTO,GLOSA_PRODUCTO,CANTIDAD_SOLICITADA,OPERACION_CONTABLE,ESTADO, HDGCODIGO, ESACODIGO, CMECODIGO ' ||
						') values (  ' ||
						SECUENCIA_DETALLE;
						IF SECUENCIA = 0 THEN
							SRV_QUERY := SRV_QUERY || ' ,' || IN_ID;
							
							ELSE 
								SRV_QUERY := SRV_QUERY || ' ,' || SECUENCIA;
						END IF;
						SRV_QUERY := SRV_QUERY || ' ,' || VJSON.CENTROCOSTO ||
							' ,' || VJSON.IDPRESUPUESTO ||
							' ,' || VJSON.IDPRODUCTO ||
							' ,''' || VJSON.CODIGOPRODUCTO || '''' ||
							' ,''' || VJSON.GLOSAPRODUCTO || '''' ||
							' ,' || VJSON.CANTIDADSOLICITADA ||
							' ,' || VJSON.OPERACIONCONTABLE ||
							' ,' || VJSON.ESTADO ||
                            ' ,' || IN_HDG_COD ||
                            ' ,' || IN_ESA_COD ||
                            ' ,' || IN_CME_COD ||
							' )   ';

						EXECUTE IMMEDIATE SRV_QUERY;
					END IF;

					IF VJSON.ACCION = 'E' THEN
						delete CLIN_FAR_DETPLANTILLACONSUMO 
						Where ID_DETAELLE = VJSON.IDDETALLE;
					END IF;

					IF VJSON.ACCION = 'M' THEN
						UPDATE CLIN_FAR_DETPLANTILLACONSUMO
						set CENTROCOSTO = VJSON.CENTROCOSTO
						, ID_PRESUPUESTO = VJSON.IDPRESUPUESTO
						, ID_PRODUCTO = VJSON.IDPRODUCTO
						, CODIGO_PRODUCTO = VJSON.CODIGOPRODUCTO
						, GLOSA_PRODUCTO = VJSON.GLOSAPRODUCTO
						, CANTIDAD_SOLICITADA = VJSON.CANTIDADSOLICITADA
						, OPERACION_CONTABLE = VJSON.OPERACIONCONTABLE
						, ESTADO = VJSON.ESTADO
						where  ID_DETAELLE= VJSON.IDDETALLE
                        AND HDGCODIGO=IN_HDG_COD
                        AND ESACODIGO=IN_ESA_COD
                        AND CMECODIGO=IN_CME_COD;
					END IF;
				END;
			END LOOP;
        END;
    END P_GRABAR_PLANTILLA_CONSUMO;
END PKG_GRABAR_PLANTILLA_CONSUMO;
/