create or replace PACKAGE PKG_ESTADO_VIGENTE_BODEGA as
    PROCEDURE P_ESTADO_VIGENTE_BODEGA(
		IN_PI_COD_BOD IN NUMBER,
    IN_HDG_COD IN NUMBER,
    IN_ESA_COD IN NUMBER,
    IN_CME_COD IN NUMBER
    );
END PKG_ESTADO_VIGENTE_BODEGA;
/
create or replace PACKAGE BODY PKG_ESTADO_VIGENTE_BODEGA AS

    PROCEDURE P_ESTADO_VIGENTE_BODEGA(
		IN_PI_COD_BOD IN NUMBER,
    IN_HDG_COD IN NUMBER,
    IN_ESA_COD IN NUMBER,
    IN_CME_COD IN NUMBER
    ) AS
    BEGIN
		  UPDATE CLIN_FAR_BODEGAS SET fbod_estado = 'S' WHERE fbod_codigo = IN_PI_COD_BOD And HDGCodigo = IN_HDG_COD AND ESACodigo = IN_ESA_COD And CMECodigo = IN_CME_COD;
    END P_ESTADO_VIGENTE_BODEGA;
END PKG_ESTADO_VIGENTE_BODEGA;
/
