create or replace PACKAGE PKG_LISTAR_MOVIMIENTO_INTERFAZ_BODEGAS_CAB as
    PROCEDURE P_LISTAR_MOVIMIENTO_INTERFAZ_BODEGAS_CAB(
		IN_HDG_CODIGO IN NUMBER,
		IN_ESA_CODIGO IN NUMBER,
		IN_CME_CODIGO IN NUMBER,
		IN_FECHA_INICIO IN VARCHAR2,
		IN_FECHA_TERMINO IN VARCHAR2,
        OUT_CURSOR IN OUT SYS_REFCURSOR
    );
END PKG_LISTAR_MOVIMIENTO_INTERFAZ_BODEGAS_CAB;
/
create or replace PACKAGE BODY PKG_LISTAR_MOVIMIENTO_INTERFAZ_BODEGAS_CAB AS

    PROCEDURE P_LISTAR_MOVIMIENTO_INTERFAZ_BODEGAS_CAB(
		IN_HDG_CODIGO IN NUMBER,
		IN_ESA_CODIGO IN NUMBER,
		IN_CME_CODIGO IN NUMBER,
		IN_FECHA_INICIO IN VARCHAR2,
		IN_FECHA_TERMINO IN VARCHAR2,
        OUT_CURSOR IN OUT SYS_REFCURSOR
    ) AS
        SRV_QUERY VARCHAR2(6000);
    BEGIN
        SRV_QUERY := ' SELECT ' ||
			'  NVL(MOV.MOVF_ID,0) AS ID ' ||
			' , NVL(MOV.HDGCODIGO,0) AS HDGCODIGO ' ||
			' , NVL(MOV.ESACODIGO,0) AS ESACODIGO ' ||
			' , NVL(MOV.CMECODIGO,0) AS CMECODIGO ' ||
			' , NVL(MOV.MOVF_SOLI_ID,0) AS SOLIID ' ||
			' , NVL(TO_CHAR(MOV.MOVF_FECHA,''DD-MM-YYYY HH24:MM:SS''),'''') AS FECHA ' ||
			' , NVL(MOV.MOVF_TIPO,0) AS CODTIPMOV ' ||
			' , NVL((SELECT PRM.FPAR_DESCRIPCION FROM CLIN_FAR_PARAM PRM WHERE PRM.FPAR_TIPO = 8 AND PRM.FPAR_CODIGO = MOV.MOVF_TIPO),'' '') AS TIPOMOVIMIENTO ' ||
			' , NVL(MOV.MOVF_BOD_ORIGEN,0) AS BODEGAORIGEN ' ||
			' , NVL((SELECT BOD.FBOD_DESCRIPCION FROM CLIN_FAR_BODEGAS BOD WHERE BOD.FBOD_CODIGO = MOV.MOVF_BOD_ORIGEN),'''') AS CODBODEGAORIGEN ' ||
			' , NVL(MOV.MOVF_BOD_DESTINO,0) AS BODEGADESTINO ' ||
			' , NVL((SELECT BOD.FBOD_DESCRIPCION FROM CLIN_FAR_BODEGAS BOD WHERE BOD.FBOD_CODIGO = MOV.MOVF_BOD_DESTINO),'''') AS CODBODEGADESTINO ' ||
			' , NVL(MOV.INT_ERP_REFERENCIA,0) AS REFERENCIACONTABLE ' ||
			' , NVL(MOV.INT_ERP_ESTADO,'''') AS INTERPESTADO ' ||
			' , NVL(MOV.INT_ERP_ERROR,'''') AS INTERPERROR ' ||
			' , NVL((SELECT max(MFDE_AGRUPADOR_ID) FROM CLIN_FAR_MOVIMDET WHERE MFDE_MOVF_ID = MOV.MOVF_ID AND MFDE_TIPO_MOV = MOV.MOVF_TIPO), 0) AS AGRUPADOR ' ||
			' FROM CLIN_FAR_MOVIM MOV ' ||
			' WHERE MOV.MOVF_SOLI_ID IN (SELECT DISTINCT(MFDE_SOLI_ID) FROM CLIN_FAR_MOVIMDET WHERE MFDE_TIPO_MOV IN (16,17,30,32,50,63,100,105,116,117)) ' ||
			'     AND MOV.HDGCODIGO = ' || IN_HDG_CODIGO ||
			'     AND MOV.ESACODIGO = ' || IN_ESA_CODIGO ||
			'     AND MOV.CMECODIGO = ' || IN_CME_CODIGO ||
			'     AND MOV.MOVF_TIPO NOT IN (404) ' ||
			'     AND (mov.movf_estid = 0 OR mov.movf_estid is null) ' ||
			'     AND MOV.MOVF_FECHA BETWEEN TO_DATE(''' || IN_FECHA_INICIO || ' 00:00:00'',''YYYY-MM-DD HH24:MI:SS'') AND TO_DATE (''' || IN_FECHA_TERMINO || ' 23:59:59'' ,''YYYY-MM-DD HH24:MI:SS'') ' ||
			' ORDER BY MOV.MOVF_FECHA ';

		-- NTRACELOG_PKG.graba_log('PKG_BUSCA_PLANTILLAS',
		--                                 null
		--             ,null
		--             ,SRV_QUERY);
        
        OPEN OUT_CURSOR FOR SRV_QUERY;

    END P_LISTAR_MOVIMIENTO_INTERFAZ_BODEGAS_CAB;
END PKG_LISTAR_MOVIMIENTO_INTERFAZ_BODEGAS_CAB;
/
