create or replace PACKAGE PKG_BUSCAR_CENTRO_COSTO_USUARIOS as
    PROCEDURE P_BUSCAR_CENTRO_COSTO_USUARIOS(
		IN_ID_USUARIO IN NUMBER,
		IN_HDG_CODIGO IN NUMBER,
		IN_ESA_CODIGO IN NUMBER,
		IN_CME_CODIGO IN NUMBER,
        OUT_CURSOR IN OUT SYS_REFCURSOR
    );

END PKG_BUSCAR_CENTRO_COSTO_USUARIOS;
/
create or replace PACKAGE BODY PKG_BUSCAR_CENTRO_COSTO_USUARIOS AS

    PROCEDURE P_BUSCAR_CENTRO_COSTO_USUARIOS(
        IN_ID_USUARIO IN NUMBER,
		IN_HDG_CODIGO IN NUMBER,
		IN_ESA_CODIGO IN NUMBER,
		IN_CME_CODIGO IN NUMBER,
        OUT_CURSOR IN OUT SYS_REFCURSOR
    ) AS
        SRV_QUERY VARCHAR2(6000);
    BEGIN
        SRV_QUERY := 'select ID_USUARIO,ID_CENTROCOSTO,HDGCODIGO,CLIN_FAR_CENTROCOSTO_USUARIOS.ESACODIGO,CMECODIGO, GLO_UNIDADES_ORGANIZACIONALES.DESCRIPCION ' ||
			'from CLIN_FAR_CENTROCOSTO_USUARIOS,GLO_UNIDADES_ORGANIZACIONALES   where  UNOR_TYPE=''CCOS'' and UNOR_CORRELATIVO= ID_CENTROCOSTO and vigente=''S'' ' ||
			' AND   CLIN_FAR_CENTROCOSTO_USUARIOS.ID_USUARIO = '|| IN_ID_USUARIO ||
			' and   CLIN_FAR_CENTROCOSTO_USUARIOS.esacodigo = GLO_UNIDADES_ORGANIZACIONALES.esacodigo';

		IF IN_HDG_CODIGO <> 0 THEN
			SRV_QUERY := SRV_QUERY || ' AND CLIN_FAR_CENTROCOSTO_USUARIOS.HDGCODIGO = ' || IN_HDG_CODIGO;
		END IF;

		IF IN_ESA_CODIGO <> 0 THEN
			SRV_QUERY := SRV_QUERY || ' AND CLIN_FAR_CENTROCOSTO_USUARIOS.ESACODIGO = ' || IN_ESA_CODIGO;
		END IF;

		IF IN_CME_CODIGO <> 0 THEN
			SRV_QUERY := SRV_QUERY || ' AND CLIN_FAR_CENTROCOSTO_USUARIOS.CMECODIGO = ' || IN_CME_CODIGO;
		END IF;

		-- NTRACELOG_PKG.graba_log('PKG_BUSCAR_CENTRO_COSTO_USUARIOS',
		--                                 null
		--             ,null
		--             ,SRV_QUERY);
        
        OPEN OUT_CURSOR FOR SRV_QUERY;

    END P_BUSCAR_CENTRO_COSTO_USUARIOS;
END PKG_BUSCAR_CENTRO_COSTO_USUARIOS;
/
