import {Detallelote} from "../entity/Detallelote"
import { TipoRechazo } from './TipoRechazo';

export class DetalleSolicitud {
    constructor(
        public sodeid             ?: number,
        public soliid             ?: number,
        public redeid             ?: number,
        public repoid             ?: number,
        public codmei             ?: string,
        public stock              ?: number,
        public meinid             ?: number,
        public unidad             ?: string,
        public dosis              ?: number,
        public formulacion        ?: number,
        public meindescri         ?: string,
        public dias               ?: number,
        public cantsoli           ?: number,
        public pendientedespacho  ?: number,
        public cantdespachada     ?: number,
        public cantidadpagadacaja ?: number,
        public cantadespachar     ?: number,
        public estado             ?: number,
        public observaciones      ?: string,
        public stockorigen        ?: number,
        public tipobodsolicitante ?: string,
        public stockdestino       ?: number,
        public tipobodsuministro  ?: string,
        public usuariomodifica    ?: string,
        public fechamodifica      ?: string,
        public usuarioelimina     ?: string,
        public fechaelimina       ?: string,
        public viaadministracion  ?: string,
        public acciond            ?: string,
        public marca              ?: string,
        public cantdevolucion     ?: number,
        public fechavto           ?: string,
        public lote               ?: string,
        public descunidadmedida   ?: string,
        public cantrecepcionado   ?: number,
        public cantrecepcionada   ?: number,
        public cantidadarecepcionar ?:number,
        public cantidadadevolver ?: number,
        public unidadcompra      ?: number,
        public unidaddespacho    ?: number,
        public glosaunidadcompra ?: string,
        public glosaunidaddespacho ?:string,
        public tiporegmein       ?: string,
        public marcacheckgrilla  ?: boolean,
        public recetaentregaprogdet ?: string,
        public diasentregacodigodet ?: number,
        public tienelote         ?: string,
        public backgroundcolor   ?: string,
        public controlado        ?: string,
        public consignacion      ?: string,
        public detallelote       ?: Detallelote[],
        public nomplantilla      ?: string,
        public idplantilla       ?: number,
        public sodecantrecepdevo ?: number,
        public cantadespacharresp?: number,
        public bloqcampogrilla   ?: boolean,
        public bloqcampogrilla2  ?: boolean,
        public excedecant        ?: boolean,
        public marcacheckgrillapro?: boolean,
        public bloqcampogrilla3  ?: boolean,
        public sodecantadev      ?: number,
        public cantidadarecepcionarresp?: number,
        public cantidadarechazar ?: number,
        public codtiporechazo    ?: number,
        public bloqcampogrilla4  ?: boolean,
        public tiporechazo       ?: TipoRechazo[],

        public estadosolicitudde ?: number,
        public fechacreacion     ?: string,
        public nombrespac        ?: string,
        public apepaternopac     ?: string,
        public apematernopac     ?: string,
        public pzagloza          ?: string,
        public camglosa          ?: string,
        public undglosa          ?: string,
        public posologia         ?: string,
        public referencia        ?: number,

    ) {
        this.excedecant = false;
    }
}
