export class DevolucionCompras{
    constructor (
        
      public fechadocrecephas     ?: string,
      public fechadocrecepdes     ?: string,
      public numerorutprov        ?: number,
      public dvrutprov            ?: string,
      public numdocto             ?: number,
      public montototaldocto      ?: number,
      public cantidaditem         ?: number,
      public fechadoc             ?: string,
      public descripcionprov      ?: string,
      public giro                 ?: string,
      public direccionprov        ?: string,
      public ciudadcodigo          ?: number,
      public ciudaddescripcion    ?: string,
      public comunacodigo          ?: number,
      public comunadesdescripcion ?: string,
      public telefono             ?: string,      
      public telefono2            ?: number,
      public diremail             ?: number,
      public ocdetnrodocto        ?: number,
      public fechanotacredito     ?: string,
      public nomproveedor         ?: string,
      public guiamontototal       ?: number,
      public guiafechaemision     ?: string,
      public numerodocrecep       ?: number,
      public proveedorid          ?: number,
      public guiatipodocto        ?: number,
      public tipodocumento        ?: number,
      public ocdetmovdetid        ?: number,
      public ocdetcant            ?: number,
      public occantadevol         ?: number,
      public ocdetmovid           ?: number,
      public ocdetmeinid          ?: number,
      public ocdetmfdeid          ?: number        
    ) {}
}