export class IngresoOrdenesCompra{
    constructor (
        
        public idmein           ?: string,
        public mein             ?: number,
        public idprov           ?: string,
        public proveedorid      ?: number,
        public orcoid           ?: number,
        public hdgcodigo        ?: number,
        public esacodigo        ?: number,
        public cmecodigo        ?: number,
        public numerodococ      ?: number,
        public fechadococ       ?: string,
        public cantidaditem     ?: number,
        public estadooc         ?: number,
        public fechaanulacionoc ?: string,
        public valorcosto       ?: number,
        public numerorutprov    ?: number,
        public dvrutprov        ?: string,
        public descripcionprov  ?: string,
        public direccionprov    ?: string,
        public contactoprov     ?: string,
        public formapago        ?: number,
        public montominfac      ?: number,
        public descestadooc     ?: string,
        public fechaemisionoc   ?: string,
        public doctosasoc       ?: string,
        public ocdetestdes      ?: string,
        public ocdetcodmei      ?: string,
        public ocdetcoddes      ?: string,
        public ocdettipoitem    ?: string,
        public ocdetcantreal    ?: number,
        public ocdetcantdev     ?: number,
        public ocdetcantmovi    ?: number,
        public ocdetvalcosto    ?: number,
        public descripcion      ?: string,
        public ocdetestado      ?: number,
        public codigo           ?: string,
        public tiporegistro     ?: string,
        public estado           ?: number,
        public fechahasta       ?: string,
        public giro             ?: string
    ) {}
}