export class InventarioDetalle {
  constructor(
    public hdgcodigo?: number,
    public esacodigo?: number,
    public cmecodigo?: number,
    public ajusteinvent?: number,
    public campo?: string,
    public codigomein?: string,
    public conteomanual1?: number,
    public conteomanual2?: number,
    public conteomanual3?: number,
    public habilitarconteo?: number,
    public actualizacionconteo1?: string,
    public actualizacionconteo2?: string,
    public actualizacionconteo3?: string,
    public useridcierre1?:number,
    public useridcierre2?:number,
    public useridcierre3?:number,
    public estadoajuste?: string,
    public fechacierre?: string,
    public iddetalleinven?: number,
    public idinventario?: number,
    public idmeinid?: number,
    public productodesc?: string,
    public stockinvent?: number,
    public valorcosto?: number,
    public servidor?: string,
    public usuario?: string,
    public tipomotivoajus?: number,
    public codigocums?: string,
    public lote?: string,
    public fechavencimiento?: string,
    public concentracion?: string,
    public formafarma?: string,
    public unidadmedida?: string,
    public update?: boolean,
    public create?: boolean,
  ) { }
}
