import { ArticuloProv } from "./ArticuloProv";

export class Proveedores {
    constructor(
        public listamein ?: string,
        public proveedorid      ?: number,
        public numerorutprov    ?: number,
        public dvrutprov        ?: string,
        public descripcionprov  ?: string,
        public direccionprov    ?: string,
        public contactoprov     ?: string,
        public formapago        ?: number,
        public montominfac      ?: number,
        public giro             ?: string,
        public ciudaddescripcion        ?: string,
        public ciudadcodigo     ?: number,
        public comunadesdescripcion        ?: string,
        public comunacodigo     ?: number,
        public paisdescripcion        ?: string,
        public paiscodigo     ?: number,
        public regiondesdescripcion        ?: string,
        public regioncodigo     ?: number,
        public telefono         ?: number,
        public telefono2        ?: number,
        public diremail         ?: string,
        public observaciones    ?: string,
        public telefono1contac  ?: number,
        public telefono2contac  ?: number,
        public representante    ?: string,
        public direccionurl     ?: string,
        public servidor?: string,
        public facturaelectr    ?: string,
        public vigenciacod      ?: number,
        public provdetalle ?: ArticuloProv[],
    ) { }
}