export class RecepcionOrdenesCompra{
    constructor (
        public orcoid           ?: number,
        public numerodococ      ?: number,
        public hdgcodigo        ?: number,
        public esacodigo        ?: number,
        public cmecodigo        ?: number,
        public codigo           ?: string,
        public ocdetmeinid      ?: number,
        public fechadococ       ?: string,
        public cantidaditem     ?: number,
        public proveedorid      ?: number,
        public estadooc         ?: number,
        public descripcion      ?: string,
        public fechaanulacionoc ?: string,
        public numerorutprov    ?: number,
        public dvrutprov        ?: string,
        public descripcionprov  ?: string,
        public direccionprov    ?: string,
        public contactoprov     ?: string,
        public formapago        ?: number,
        public formapagodes     ?: string,
        public montominfac      ?: number,
        public descestadooc     ?: string,
        public fechaemisionoc   ?: string,
        public doctosasoc       ?: string,
        public ocdetestdes      ?: string,
        public ocdetcodmei      ?: string,
        public ocdetcoddes      ?: string,
        public ocdettipoitem    ?: string,
        public ocdetcantreal    ?: number,
        public ocdetcantrecep   ?: number,
        public ocdetcantdev     ?: number,
        public ocdetcantmovi    ?: number,
        public ocdetvalcosto    ?: number,
        public ocdetid          ?: number,
        public doctoaingresar   ?: number,
        public montodocto       ?: number,
        public fecharecepcion   ?: Date,
        public fechadocto       ?: Date,
        public preciodocto      ?: number,
        public cantidadaingresar?: number,
        public fechavencimiento ?: string,
        public giro             ?: string,
        public ciudaddes        ?: string,
        public comunades        ?: string
        
    ) {}
}