import { DetalleRecetas } from './detalle-recetas';
import { DetalleRecetasModal } from './detalle-recetas-modal';

export class Receta {
    constructor (
        public servidor             ?: string,
        public usuario              ?: string,
        public cliid                ?: string,
        public fechainicio          ?: string,
        public fechahasta           ?: string,
        public receid               ?: number,
        public hdgcodigo            ?: number,
        public esacodigo            ?: number,
        public cmecodigo            ?: number,
        public receambito           ?: number,
        public recetipo             ?: string,
        public recenumero           ?: number,
        public recesubreceta        ?: number,
        public recefecha            ?: string,
        public recefechaentrega     ?: string,
        public fichapaci            ?: number,
        public recectaid            ?: number,
        public receurgid            ?: number,
        public recedau              ?: number,
        public rececliid            ?: number,
        public recetipdocpac        ?: number,
        public recedocumpac         ?: string,
        public recetipdocprof       ?: number,
        public recedocumprof        ?: string,
        public receespecialidad     ?: string,
        public recerolprof          ?: string,
        public recesolid            ?: number,
        public receestadodespacho   ?: number,
        public recenombrepaciente   ?: string,
        public recenombremedico     ?: string,
        public rececodunidad        ?: string,
        public rececodservicio      ?: string,
        public receglosaunidad      ?: string,
        public receglosaservicio    ?: string,
        public rececodigocama       ?: string,
        public receglosacama        ?: string,
        public rececodigopieza      ?: string,
        public receglosapieza       ?: string,
        public recetipdocpacglosa   ?: string,
        public clinombres           ?: string,
        public cliapepaterno        ?: string,
        public cliapematerno        ?: string,
        public cajanumerocomprobante?: number,
        public cajaidcomprobante    ?: number,
        public cajafechacomprobante ?: string,
        public codigoestadocomprobante?: string,
        public glosaestadocomprobante?: string,
        public pestid               ?: number,
        public ctanumcta            ?: number,
        public recetadetalle        ?: DetalleRecetas[],
        public recetadetallemodal   ?: DetalleRecetasModal[],
        public profnombre           ?: string,
        public profapepaterno       ?: string,
        public profapematerno       ?: string,
        public receobservacion      ?: string,
        public glsexo               ?: string,
        public edad                 ?: string,
        public bandera              ?: number,
        public codcobroincluido     ?: number,
        public glosacobro           ?: string,
        public rececodbodega        ?: number,
        public cuentanumcuenta      ?: string,
        public estadoreceta         ?: string,
        public plancotizante        ?: string,
        public bonificacion         ?: string,
    ) {}
}
