export class ReposicionArticulos{
    constructor (
        public hdgcodigo        ?: number,
        public esacodigo        ?: number,
        public cmecodigo        ?: number,
        public codmei           ?: string,
        public codigomein       ?: string,
        public codmeinid        ?: number,
        public meinid           ?: number,
        public codigo           ?: string,
        public descripcion      ?: string,
        public meindescri       ?: string,
        public descripcionmein  ?: string,
        public tiporegistro     ?: number,
        public tipomedicamento  ?: number,
        public valorcosto       ?: number,
        public margenmedicamento?: number,
        public valorventa       ?: number,
        public unidadcompra     ?: string,
        public unidaddespacho   ?: string,
        public incobfonasa      ?: string,
        public tipoincob        ?: string,
        public estado           ?: number,
        public clasificacion    ?: number,
        public recetaretenida   ?: string,
        public solocompra       ?: string,
        public preparados       ?: string,
        public usuario          ?: string,
        public servidor         ?: string,
        public codpact          ?: number,
        public codpres          ?: number,
        public codffar          ?: number,
        public cantidadareponer ?: number,
        public marca            ?: string,
        public mfdeid           ?: number,
        public stockactual      ?: number,
        public fechamov         ?: string,
        public fechacreacion    ?: string,
        public cantsoli         ?: number,
        public cantidadareponerresp?: number,
        public stocksuministro ?: number,        
        public mostrarError ?: boolean,        
    ) {}
}

