package models

// Receta is...
type Receta struct {
	SERVIDOR                 string               `json:"servidor"`
	USUARIO                  string               `json:"usuario"`
	FECHAINICIO              string               `json:"fechainicio"`
	FECHAHASTA               string               `json:"fechahasta"`
	RECEID                   int                  `json:"receid"`
	HDGCODIGO                int                  `json:"hdgcodigo"`
	ESACODIGO                int                  `json:"esacodigo"`
	CMECODIGO                int                  `json:"cmecodigo"`
	RECEAMBITO               int                  `json:"receambito"`
	RECETIPO                 string               `json:"recetipo"`
	RECENUMERO               int                  `json:"recenumero"`
	RECESUBRECETA            int                  `json:"recesubreceta"`
	RECEFECHA                string               `json:"recefecha"`
	RECEFECHAENTREGA         string               `json:"recefechaentrega"`
	RECEFICHAPACI            int                  `json:"fichapaci"`
	RECECTAID                int                  `json:"recectaid"`
	RECEURGID                int                  `json:"receurgid"`
	RECEDAU                  int                  `json:"recedau"`
	RECECLIID                int                  `json:"rececliid"`
	RECETIPDOCPAC            int                  `json:"recetipdocpac"`
	RECEDOCUMPAC             string               `json:"recedocumpac"`
	RECETIPDOCPROF           int                  `json:"recetipdocprof"`
	RECEDOCUMPROF            string               `json:"recedocumprof"`
	RECEESPECIALIDAD         string               `json:"receespecialidad"`
	RECEROLPROF              string               `json:"recerolprof"`
	RECESOLID                int                  `json:"recesolid"`
	RECEESTADODESPACHO       int                  `json:"receestadodespacho"`
	RECENOMBREPACIENTE       string               `json:"recenombrepaciente"`
	RECENOMBREMEDICO         string               `json:"recenombremedico"`
	RECECODUNIDAD            string               `json:"rececodunidad"`
	RECECODSERVICIO          string               `json:"rececodservicio"`
	RECEGLOSAUNIDAD          string               `json:"receglosaunidad"`
	RECEGLOSASERVICIO        string               `json:"receglosaservicio"`
	RECECODIGOCAMA           string               `json:"rececodigocama"`
	RECEGLOSACAMA            string               `json:"receglosacama"`
	RECECODIGOPIEZA          string               `json:"rececodigopieza"`
	RECEGLOSAPIEZA           string               `json:"receglosapieza"`
	RECETIPDOCPACGLOSA       string               `json:"recetipdocpacglosa"`
	CLINOMBRES               string               `json:"clinombres"`
	CLIAPEPATERNO            string               `json:"cliapepaterno"`
	CLIAPEMATERNO            string               `json:"cliapematerno"`
	CAJANUMEROCOMPROBANTE    int                  `json:"cajanumerocomprobante"`
	CAJAIDCOMPROBANTE        int                  `json:"cajaidcomprobante"`
	CAJAFECHACOMPROBANTECHAR string               `json:"cajafechacomprobante"`
	CODIGOESTADOCOMPROBANTE  string               `json:"codigoestadocomprobante"`
	GLOSAESTADOCOMPROBANTE   string               `json:"glosaestadocomprobante"`
	PESTID                   int                  `json:"pestid"`
	CTANUMCUENTA             int                  `json:"ctanumcta"`
	PROFNOMBRE               string               `json:"profnombre"`
	PROFAPEPATERNO           string               `json:"profapepaterno"`
	PROFAPEMATERNO           string               `json:"profapematerno"`
	RECEOBSERVACION          string               `json:"receobservacion"`
	EDAD                     string               `json:"edad"`
	SEXO                     string               `json:"glsexo"`
	BANDERA                  int                  `json:"bandera"`
	CODCOBROINCLUIDO         int                  `json:"codcobroincluido"`
	GLOSACOBRO               string               `json:"glosacobro"`
	CODBODEGA                int                  `json:"rececodbodega"`
	PlanCotizante            string               `json:"plancotizante"`
	Bonificacion             string               `json:"bonificacion"`
	RECETADETALLE            []RecetaDetalle      `json:"recetadetalle"`
	RECEESTADORECETA         string               `json:"estadoreceta"`
	RECETADETALLEMODAL       []RecetaDetalleModal `json:"recetadetallemodal"`
}
