package models

// Solicitudes is...
type Solicitudes struct {
	SoliID                int              `json:"soliid"`
	HDGCodigo             int              `json:"hdgcodigo"`
	ESACodigo             int              `json:"esacodigo"`
	CMECodigo             int              `json:"cmecodigo"`
	CliID                 int              `json:"cliid"`
	TipoDocPac            int              `json:"tipodocpac"`
	NumDocPac             string           `json:"numdocpac"`
	ApePaternoPac         string           `json:"apepaternopac"`
	ApeMaternoPac         string           `json:"apematernopac"`
	NombresPac            string           `json:"nombrespac"`
	CodAmbito             int              `json:"codambito"`
	EstID                 int              `json:"estid"`
	CtaID                 int              `json:"ctaid"`
	EdadPac               int              `json:"edadpac"`
	TipoEdad              string           `json:"tipoedad"`
	CodSex                int              `json:"codsexo"`
	CodServicioOri        int              `json:"codservicioori"`
	CodServicioDes        int              `json:"codserviciodes"`
	BodOrigen             int              `json:"bodorigen"`
	BodDestino            int              `json:"boddestino"`
	TipoBodOrigen         string           `json:"tipobodorigen"`
	TipoBodDestino        string           `json:"tipoboddestino"`
	TipoProducto          int              `json:"tipoproducto"`
	TipoReceta            string           `json:"tiporeceta"`
	NumeroReceta          float64          `json:"numeroreceta"`
	TipoMovim             string           `json:"tipomovim"`
	TipoSolicitud         int              `json:"tiposolicitud"`
	EstadoSolicitud       int              `json:"estadosolicitud"`
	PrioridadSoli         int              `json:"prioridadsoli"`
	TipoDocProf           int              `json:"tipodocprof"`
	NumDocProf            string           `json:"numdocprof"`
	Alergias              string           `json:"alergias"`
	Cama                  string           `json:"cama"`
	FechaCreacion         string           `json:"fechacreacion"`
	UsuarioCreacion       string           `json:"usuariocreacion"`
	FechaModifica         string           `json:"fechamodifica"`
	UsuarioModifica       string           `json:"usuariomodifica"`
	FechaElimina          string           `json:"fechaelimina"`
	UsuarioElimina        string           `json:"usuarioelimina"`
	FechaCierre           string           `json:"fechacierre"`
	UsuarioCierre         string           `json:"usuariocierre"`
	Observaciones         string           `json:"observaciones"`
	PPNPaciente           int              `json:"ppnpaciente"`
	Convenio              string           `json:"convenio"`
	Diagnostico           string           `json:"diagnostico"`
	NombreMedico          string           `json:"nombremedico"`
	CuentaNumCta          string           `json:"cuentanumcuenta"`
	BodOrigenDesc         string           `json:"bodorigendesc"`
	BodDestinoDesc        string           `json:"boddestinodesc"`
	Usuario               string           `json:"usuario"`
	Servidor              string           `json:"servidor"`
	Accion                string           `json:"accion"`
	OrigenSolicitud       int              `json:"origensolicitud"`
	EstadoSolicitudDe     string           `json:"estadosolicitudde"`
	DesPrioridadSoli      string           `json:"desprioridadsoli"`
	DesOrigenSolicitud    string           `json:"desorigensolicitud"`
	SOLICODPIEZA          string           `json:"codpieza"`
	SOLIIDCAMA            int              `json:"camid"`
	SOLIIDPIEZA           int              `json:"piezaid"`
	Glsexo                string           `json:"glsexo"`
	Glstipidentificacion  string           `json:"glstipidentificacion"`
	Glsambito             string           `json:"glsambito"`
	Undglosa              string           `json:"undglosa"`
	Camglosa              string           `json:"camglosa"`
	Pzagloza              string           `json:"pzagloza"`
	Edad                  string           `json:"edad"`
	Comprobantecaja       string           `json:"comprobantecaja"`
	Estadocomprobantecaja int              `json:"estadocomprobantecaja"`
	Boleta                float64          `json:"boleta"`
	CodServicioActual     string           `json:"codservicioactual"`
	RecetaEntregaProg     string           `json:"recetaentregaprog"`
	DiasEntregaCodigo     int              `json:"diasentregacodigo"`
	SoliTipoReg           string           `json:"solitiporeg"`
	Controlado            string           `json:"controlado"`
	Consignacion          string           `json:"consignacion"`
	IDPlantilla           int              `json:"idplantilla"`
	SOLIRECETIPO          string           `json:"solirecetipo"`
	FiltroDeNegocio       string           `json:"filtronegocio"`
	NroPedidoFin700Erp    int              `json:"nropedidofin700erp"`
	ErrorErp              string           `json:"errorerp"`
	RECEID                int              `json:"receid"`
	Bandera               int              `json:"bandera"`
	TipoBodSolicitante    string           `json:"tipobodsolicitante"`
	TipoBodSuministro     string           `json:"tipobodsuministro"`
	Referencia            int              `json:"referencia"`
	NumPedido             int              `json:"numpedido"`
	PlanCotizante         string           `json:"plancotizante"`
	Bonificacion          string           `json:"bonificacion"`
	Pagina                int              `json:"pagina"`
	Mensaje               Mensaje          `json:"mensaje"`
	Detalle               []SolicitudesDet `json:"solicitudesdet"`
}

// SolicitudesDet is...
type SolicitudesDet struct {
	SodeID                int           `json:"sodeid"`
	SoliID                int           `json:"soliid"`
	CodMei                string        `json:"codmei"`
	MeInID                int           `json:"meinid"`
	Dosis                 int           `json:"dosis"`
	Formulacion           int           `json:"formulacion"`
	Dias                  int           `json:"dias"`
	CantSoli              int           `json:"cantsoli"`
	CantDespachada        int           `json:"cantdespachada"`
	CantDevolucion        int           `json:"cantdevolucion"`
	Estado                int           `json:"estado"`
	Observaciones         string        `json:"observaciones"`
	FechaModifica         string        `json:"fechamodifica"`
	UsuarioModifica       string        `json:"usuariomodifica"`
	FechaElimina          string        `json:"fechaelimina"`
	UsuarioElimina        string        `json:"usuarioelimina"`
	ViaAdministracion     string        `json:"viaadministracion"`
	MeInDescri            string        `json:"meindescri"`
	StockOrigen           int           `json:"stockorigen"`
	StockDestino          int           `json:"stockdestino"`
	AccionD               string        `json:"acciond"`
	CantADespachar        int           `json:"cantadespachar"`
	FparDescripcionUnidad string        `json:"descunidadmedida"`
	CodViaAdm             int           `json:"codviaadm"`
	DesViaAdm             string        `json:"desviaadm"`
	CantRecepcionado      int           `json:"cantrecepcionado"`
	TipoRegMeIn           string        `json:"tiporegmein"`
	RecetaEntregaProgDet  string        `json:"recetaentregaprogdet"`
	DiasEntregaCodigoDet  int           `json:"diasentregacodigodet"`
	TieneLote             string        `json:"tienelote"`
	Controlado            string        `json:"controlado"`
	Consignacion          string        `json:"consignacion"`
	SODECANTRECEPDEVO     int           `json:"sodecantrecepdevo"`
	SodeCantADev          int           `json:"sodecantadev"`
	TipoBodSolicitante    string        `json:"tipobodsolicitante"`
	TipoBodSuministro     string        `json:"tipobodsuministro"`
	Posologia             string        `json:"posologia"`
	DetalleLote           []DetalleLote `json:"detallelote"`
}

// DetalleLote is...
type DetalleLote struct {
	Lote     string `json:"lote"`
	FechaVto string `json:"fechavto"`
	Saldo    int    `json:"cantidad"`
	GlsCombo string `json:"glscombo"`
}
