ALTER TABLE CLIN_FAR_MAMEIN MODIFY MEIN_CODMEI VARCHAR2(25);

ALTER TABLE CLIN_FAR_MAMEIN ADD MEIN_GRUPO NUMBER(12) NULL;

ALTER TABLE CLIN_FAR_MAMEIN ADD MEIN_SUBGRUPO NUMBER(12) NULL;

ALTER TABLE CLIN_FAR_MAMEIN ADD MEIN_CLASIFICACION NUMBER(12) NULL;

COMMENT ON COLUMN "CLIN_FAR_MAMEIN"."MEIN_GRUPO" IS 'ID de Tabla clin_far_grupoconsumo';

COMMENT ON COLUMN "CLIN_FAR_MAMEIN"."MEIN_SUBGRUPO" IS 'ID de Tabla clin_far_subgrupoconsumo';

COMMENT ON COLUMN "CLIN_FAR_MAMEIN"."MEIN_CLASIFICACION" IS 'ID de Tabla CLIN_FAR_MAMEIN_CLASIFICACION';

COMMIT;