alter table clin_far_recetas add (rece_cod_cobro_incluido Number(3,0) Default (0) null);

ALTER TABLE CLIN_FAR_RECETAS ADD (RECE_CODTIPIDENTIFICACION_RETIRA NUMBER (8,0) NULL,RECE_NUMIDENTIFICACION_RETIRA  VARCHAR2(20 BYTE) NULL,RECE_NOMBRES_RETIRA VARCHAR2(200 BYTE) NULL);

