ALTER TABLE CLIN_FAR_PRESTAMOS_MOV ADD ( FPMO_CODIGO_CUM VARCHAR2(20 BYTE) NULL, FPMO_REGISTRO_INVIMA VARCHAR2(20 BYTE) NULL, FPMO_LOTE VARCHAR2(20 BYTE) NULL, FPMO_FECHAVTO DATE NULL );

ALTER TABLE CLIN_FAR_PRESTAMOS_DET ADD (FPDE_LOTE VARCHAR2(20 BYTE) NULL, FPDE_FECHAVTO DATE NULL);

ALTER TABLE CLIN_FAR_PRESTAMOS ADD (FPRE_USUARIO_CIERRE VARCHAR2(30 BYTE) NULL, FPRE_OBSERVACIONES_CIERRE VARCHAR2(200 BYTE) NULL);
