-- (1) Crear columnas para el HES
ALTER TABLE CLIN_FAR_PARAM 
ADD (
    FPAR_HDGCODIGO NUMBER(8,0), 
    FPAR_ESACODIGO NUMBER(8,0), 
    FPAR_CMECODIGO NUMBER(8,0)
);

COMMENT ON COLUMN "FARMACIACLINICA"."CLIN_FAR_PARAM"."FPAR_HDGCODIGO" IS 'Codigo de HOLDING. Todo el HES en 0 para que sea general.';
COMMENT ON COLUMN "FARMACIACLINICA"."CLIN_FAR_PARAM"."FPAR_ESACODIGO" IS 'Codigo de EMPRESA. Todo el HES en 0 para que sea general.';
COMMENT ON COLUMN "FARMACIACLINICA"."CLIN_FAR_PARAM"."FPAR_CMECODIGO" IS 'Codigo de CENTRO MEDICO (SUCURSAL). Todo el HES en 0 para que sea general.';

-- (2) Agregar HES 1-2-1 a todas las columnas para que se pueda probar en desarrollo
UPDATE CLIN_FAR_PARAM 
SET FPAR_HDGCODIGO = 1,
    FPAR_ESACODIGO = 2,
    FPAR_CMECODIGO = 1;

-- (3) Agregar restriccion para que el HES no sea nulo
ALTER TABLE CLIN_FAR_PARAM MODIFY ( FPAR_HDGCODIGO NOT NULL);
ALTER TABLE CLIN_FAR_PARAM MODIFY ( FPAR_ESACODIGO NOT NULL);
ALTER TABLE CLIN_FAR_PARAM MODIFY ( FPAR_CMECODIGO NOT NULL);

/ 

