ALTER TABLE TMP_RPT_LISTADO_ALFA_PRODUCTOS ADD (
     CODIGO_CUM VARCHAR2(20),
     LOTE VARCHAR2(20 BYTE),
     FECHA_VENCIMIENTO VARCHAR2(20 BYTE),
     PACT_DESCRI VARCHAR2(150 BYTE),
     PRES_DESCRI VARCHAR2(150 BYTE),
     FFAR_DESCRI VARCHAR2(150 BYTE),
     INVENTARIO_MANUAL_1 NUMBER(8,0),
     INVENTARIO_MANUAL_2 NUMBER(8,0),
     INVENTARIO_MANUAL_3 NUMBER(8,0),
     ) ;